//! Integration tests against the small committed fixture files in
//! `tests/fixtures/` at the workspace root (regenerated by the testkit
//! `gen_fixtures` example).

use std::path::PathBuf;

use pdfboss_core::Document;

/// Absolute path to a committed fixture file.
fn fixture(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../tests/fixtures")
        .join(name)
}

#[test]
fn open_hello_fixture() {
    let doc = Document::open(fixture("hello.pdf")).expect("hello.pdf should open");
    assert_eq!(doc.page_count(), 1);
    assert_eq!(doc.version(), (1, 7));

    let page = doc.page(0).expect("page 0 should exist");
    assert_eq!(page.size(), (612.0, 792.0));
    let content = page.content(&doc).expect("content should decode");
    let text = String::from_utf8_lossy(&content);
    assert!(text.contains("Hello, world!"), "content was: {text}");
}

#[test]
fn open_three_pages_fixture() {
    let doc = Document::open(fixture("three-pages.pdf")).expect("three-pages.pdf should open");
    assert_eq!(doc.page_count(), 3);
    for (i, expected) in ["Page one", "Page two", "Page three"].iter().enumerate() {
        let page = doc.page(i).expect("page should exist");
        let content = page.content(&doc).expect("content should decode");
        let text = String::from_utf8_lossy(&content);
        assert!(text.contains(expected), "page {i} content was: {text}");
    }
}

#[test]
fn open_xref_stream_fixture() {
    let doc = Document::open(fixture("xref-stream.pdf")).expect("xref-stream.pdf should open");
    assert_eq!(doc.page_count(), 1);
    let page = doc.page(0).expect("page 0 should exist");
    let content = page.content(&doc).expect("content should decode");
    let text = String::from_utf8_lossy(&content);
    assert!(text.contains("Hello, world!"), "content was: {text}");
}

#[test]
fn open_shapes_fixture() {
    let doc = Document::open(fixture("shapes.pdf")).expect("shapes.pdf should open");
    assert_eq!(doc.page_count(), 1);
    let page = doc.page(0).expect("page 0 should exist");
    let content = page.content(&doc).expect("content should decode");
    let text = String::from_utf8_lossy(&content);
    assert!(text.contains("re f"), "content was: {text}");
}
