import Iso32000.Checks

/-!
`lake exe iso32000-report` prints the conformance chapter of the book from the
ledger, as Markdown, to stdout. `lake exe iso32000-report --check` prints the
rows, clauses and citations that would fail the gate to stderr and exits
with 1 when there are any, so a failing `lake build` has a readable cause.
-/

open Iso32000

namespace Report

def statusLabel : Status → String
  | .implemented => "implemented"
  | .incomplete => "incomplete"
  | .notImplemented => "not implemented"
  | .outOfScope => "out of scope"

def codeCitations (f : Feature) : List Citation :=
  Generated.citations.filter fun c => !c.inTest && f.citedBy c

def testCitations (f : Feature) : List Citation :=
  Generated.citations.filter fun c => c.inTest && f.citedBy c

def cell (s : String) : String := s.replace "|" "\\|"

def rowFor (f : Feature) : String :=
  s!"| {f.ref.render} | {cell f.title} | {statusLabel f.status} | " ++
  s!"{(codeCitations f).length} | {(testCitations f).length} | {cell f.note} |"

def inOrder (features : List Feature) : List Feature :=
  (features.toArray.qsort fun a b => decide (a.ref.key < b.ref.key)).toList

def chapterFeatures (chapter : Nat) : List Feature :=
  inOrder (Catalogue.features.filter fun f => f.ref.chapter == some chapter)

def annexFeatures : List Feature :=
  inOrder (Catalogue.features.filter fun f => f.ref.chapter.isNone)

def chapterTitle (chapter : Nat) : String :=
  match Outline.chapters.find? (·.1 == chapter) with
  | some (_, title) => title
  | none => ""

def tableHeader : List String :=
  [ "| Clause | Feature | Status | Code citations | Test citations | Note |",
    "|---|---|---|---|---|---|" ]

def chapterSection (title : String) (features : List Feature) : List String :=
  if features.isEmpty then [] else
    [s!"## {title}", ""] ++ tableHeader ++ features.map rowFor ++ [""]

def countWith (status : Status) : Nat :=
  (Catalogue.features.filter (·.status == status)).length

def summary : List String :=
  [ "| Status | Rows |", "|---|---|" ] ++
  [Status.implemented, .incomplete, .notImplemented, .outOfScope].map (fun s =>
    s!"| {statusLabel s} | {countWith s} |") ++ [""]

def intro : List String := [
  "# ISO 32000 conformance",
  "",
  "pdfboss keeps a ledger of ISO 32000 clauses in `iso32000/Iso32000/Catalogue/`, one row per",
  "clause with the status pdfboss claims: implemented, incomplete, not implemented or out of",
  "scope. Clause numbers follow ISO 32000-1:2008; where ISO 32000-2:2020 numbers a clause",
  "differently the row carries both.",
  "",
  "The ledger is checked by Lean 4 on every push (`make iso32000-gate`). Six theorems in",
  "`iso32000/Iso32000/Gate.lean` establish that every row is unique, that every clause of chapters",
  "7 to 14 and the normative annexes has a row speaking to it, that every implemented row is cited",
  "by both implementation code and a test in the source tree, that every incomplete row is cited by",
  "implementation code and explains what is missing, that every other row explains itself, and that",
  "no first-edition citation names a clause the standard does not have. They are decided by Lean's",
  "compiled evaluator (`native_decide`), so they trust the Lean compiler as well as its kernel; the",
  "decode-after-encode theorems of the reference filter decoders in `iso32000/Iso32000/Reference/`,",
  "whose vectors the Rust tests replay, are checked by the kernel alone. Citation counts below are",
  "the number of source comments naming the clause or a sub-clause of it, in implementation code",
  "and in tests.",
  "",
  "This page is generated by `make iso32000-report`. Edit the ledger, not the page.",
  ""
]

def document : String :=
  let chapters := (List.range 8).map (· + 7)
  let body := chapters.flatMap (fun c => chapterSection s!"{c} {chapterTitle c}" (chapterFeatures c)) ++
    chapterSection "Annexes" annexFeatures
  "\n".intercalate (intro ++ summary ++ body)

def missingFor (f : Feature) : List String :=
  let needsCode := f.status == .implemented || f.status == .incomplete
  let needsTests := f.status == .implemented
  let needsNote := f.status != .implemented
  (if needsCode && (codeCitations f).isEmpty then ["no implementation comment cites it"] else []) ++
  (if needsTests && (testCitations f).isEmpty then ["no test cites it"] else []) ++
  (if needsNote && f.note.isEmpty then ["no note explains it"] else [])

def checkReport : List String :=
  let offenders := Gate.offenders.map fun f =>
    s!"row {f.ref.render} ({statusLabel f.status}) {f.title}: {", ".intercalate (missingFor f)}"
  let unaddressed := Gate.unaddressed.map fun h =>
    s!"clause {h.ref.render} {h.title}: no ledger row speaks to it"
  let dangling := Gate.danglingCitations.map fun c =>
    s!"{c.file}:{c.line}: cites {(c.ref.map Ref.render).getD "?"}, which the standard does not have"
  let duplicates := Gate.duplicateRefs.eraseDups.map fun r => s!"row {r.render} appears more than once"
  let misfiled := Gate.misfiledRows.map fun f => s!"row {f.ref.render} sits in another chapter's list"
  let unsliced := Gate.unslicedRows.map fun f => s!"row {f.ref.render} is in no chapter list"
  offenders ++ unaddressed ++ dangling ++ duplicates ++ misfiled ++ unsliced

end Report

def main (args : List String) : IO UInt32 := do
  if args.contains "--check" then
    let problems := Report.checkReport
    for line in problems do
      IO.eprintln line
    IO.eprintln s!"{problems.length} problem(s); {Catalogue.features.length} ledger rows, \
      {Generated.citations.length} citations"
    return if problems.isEmpty then 0 else 1
  IO.println Report.document
  return 0
