"""PDF parsing, text extraction and rendering in pure Rust."""

from enum import StrEnum

from pdfboss import md, write
from pdfboss._pdfboss import (
    Action,
    Annotation,
    AnnotationFlags,
    AppearanceCharacteristics,
    ArticleThread,
    AsyncDocument,
    ContentItem,
    AsyncElementIter,
    AsyncPage,
    AsyncSpanIter,
    Bead,
    Border,
    ChoiceOption,
    DefaultAppearance,
    Destination,
    DeveloperExtension,
    Document,
    Element,
    ElementIter,
    EmbeddedFile,
    FieldFlags,
    FileSpec,
    FormField,
    InteractiveForm,
    LegalAttestation,
    Linearization,
    Markup,
    Measure,
    NumberFormat,
    OptionalContentGroup,
    OptionalContentUsage,
    OutlineItem,
    OutputIntent,
    Page,
    PageImage,
    PageLabel,
    PagePiece,
    PdfError,
    PermissionHandlers,
    PlacedImage,
    Presentation,
    Requirement,
    RequirementHandler,
    SeparationInfo,
    Signature,
    Span,
    SpanIter,
    Target,
    Thumbnail,
    Transition,
    TriggeredAction,
    ViewerPreferences,
    Viewport,
    Widget,
    WindowsLaunch,
    __version__,
)



class ReadingOrder(StrEnum):
    """The order a page's text is read in. Every extraction method takes one
    as its ``reading_order`` keyword, as this enum or as its string value."""

    CONTENT = "content"
    """The content stream's order, corrected by geometry (the default)."""

    STRUCTURE_TREE = "structure-tree"
    """The structure tree's order on tagged pages, content order elsewhere."""

    GEOMETRIC = "geometric"
    """Position alone: lines top to bottom, spans left to right."""


__all__ = [
    "Action",
    "Annotation",
    "AnnotationFlags",
    "AppearanceCharacteristics",
    "ArticleThread",
    "AsyncDocument",
    "AsyncElementIter",
    "AsyncPage",
    "AsyncSpanIter",
    "ContentItem",
    "Bead",
    "Border",
    "ChoiceOption",
    "DefaultAppearance",
    "Destination",
    "DeveloperExtension",
    "Document",
    "Element",
    "ElementIter",
    "EmbeddedFile",
    "FieldFlags",
    "FileSpec",
    "FormField",
    "InteractiveForm",
    "LegalAttestation",
    "Linearization",
    "Markup",
    "Measure",
    "NumberFormat",
    "OptionalContentGroup",
    "OptionalContentUsage",
    "OutlineItem",
    "OutputIntent",
    "Page",
    "PageImage",
    "PageLabel",
    "PagePiece",
    "PdfError",
    "PermissionHandlers",
    "PlacedImage",
    "Presentation",
    "ReadingOrder",
    "Requirement",
    "RequirementHandler",
    "SeparationInfo",
    "Signature",
    "Span",
    "SpanIter",
    "Target",
    "Thumbnail",
    "Transition",
    "TriggeredAction",
    "ViewerPreferences",
    "Viewport",
    "Widget",
    "WindowsLaunch",
    "__version__",
    "md",
    "write",
]
