"""Composing new PDFs: pages, elements and document slots joined with |,
watermarking existing ones in place, and merging, splitting, rotating or
rewriting existing ones."""

import pdfboss._pdfboss  # noqa: F401  registers pdfboss._pdfboss.write in sys.modules
from pdfboss._pdfboss.write import (
    Attachment,
    Bookmark,
    Canvas,
    Image,
    Link,
    Metadata,
    Outline,
    Page,
    PageLabel,
    Paragraph,
    Pdf,
    Standard14,
    Text,
    Update,
    Viewer,
    merge,
    rewrite,
    rotate,
    split,
    watermark,
)

__all__ = [
    "Attachment",
    "Bookmark",
    "Canvas",
    "Image",
    "Link",
    "Metadata",
    "Outline",
    "Page",
    "PageLabel",
    "Paragraph",
    "Pdf",
    "Standard14",
    "Text",
    "Update",
    "Viewer",
    "merge",
    "rewrite",
    "rotate",
    "split",
    "watermark",
]
