import Iso32000.Feature

/-!
Ledger rows for ISO 32000-1 chapter 8, Graphics.
-/

namespace Iso32000.Catalogue

def chapter8 : List Feature := [
  { ref := .clause [8, 2], title := "Graphics Objects", status := .implemented,
    note := "Path, text, XObject, inline image and shading objects all execute, BX/EX parse and unknown operators are skipped; the object nesting rules bind writers and are not validated on read." },
  { ref := .clause [8, 3, 2, 2], title := "Device Space", status := .implemented,
    note := "The crop box, /Rotate and the scale factor build the base matrix with the y flip that puts the first device row at the top." },
  { ref := .clause [8, 3, 2, 3], title := "User Space", status := .implemented,
    note := "The page's default user space is the base matrix, cm concatenates onto the CTM and q/Q restores it." },
  { ref := .clause [8, 3, 2, 4], title := "Other Coordinate Spaces", status := .implemented,
    note := "Form, image (unit square), pattern, text and Type3 glyph spaces each map through their own matrix onto the CTM." },
  { ref := .clause [8, 3, 2, 5], title := "Relationships among Coordinate Spaces", status := .implemented,
    note := "Transformations compose by matrix concatenation from the innermost space out to device space." },
  { ref := .clause [8, 3, 3], title := "Common Transformations", status := .implemented,
    note := "Translation, scaling and rotation constructors follow the clause's matrix forms; skew is expressed through the general six-element matrix." },
  { ref := .clause [8, 3, 4], title := "Transformation Matrices", status := .implemented,
    note := "The six-element matrix, its concatenation order and inversion follow the clause; a non-finite cm operand is skipped." },
  { ref := .clause [8, 4, 1], title := "General", status := .incomplete,
    note := "Table 52's CTM, clip, colour spaces and colours, line width/cap/join/miter/dash, alpha, blend mode, soft mask and text state are tracked with the clause's initial values; rendering intent, stroke adjustment and alpha source are not, and none of Table 53 (overprint, black generation, undercolor removal, transfer, halftone, flatness, smoothness) is tracked." },
  { ref := .clause [8, 4, 2], title := "Graphics State Stack", status := .implemented,
    note := "q pushes and Q pops the whole state including clip and soft mask, a form's unbalanced Q cannot pop its caller's state (case form_with_unbalanced_restore), and nesting is capped at 64 levels." },
  { ref := .clause [8, 4, 3, 2], title := "Line Width", status := .implemented,
    note := "The pen is a user-space circle carried through the CTM (anisotropic scaling widens it correctly) and a zero or sub-pixel width paints the thinnest visible hairline; the writer emits w through canvas.rs set_line_width." },
  { ref := .clause [8, 4, 3, 3], title := "Line Cap Style", status := .implemented,
    note := "J and /LC set stroke.rs LineCap, which stroke_path reads at every run end: butt caps stop at the endpoint, round caps add the pen disc, projecting square caps carry the band on by half the line width in user space (stroke.rs butt_caps_stop_at_the_endpoints, square_caps_extend_the_band_by_half_the_width, executor.rs line_caps_follow_j_and_lc); zero-length dashes take the cap style along the path's direction; a J operand outside 0 to 2 sets butt; the writer emits J through canvas.rs set_line_cap." },
  { ref := .clause [8, 4, 3, 4], title := "Line Join Style", status := .implemented,
    note := "j and /LJ set stroke.rs LineJoin, which stroke_path reads at every interior vertex and at the start of a closed subpath: a miter carries the two bands' outer edges to their meeting point, a bevel cuts across their ends, a round join adds the pen disc; collinear segments get no join and a segment turning straight back gets only the round disc (stroke.rs miter_joins_fill_the_outer_corner, bevel_joins_cut_the_corner, round_joins_keep_the_pen_disc, joins_follow_a_flipped_matrix, executor.rs line_joins_follow_j_lj_m_and_ml); a j operand outside 0 to 2 sets miter; the writer emits j through canvas.rs set_line_join." },
  { ref := .clause [8, 4, 3, 5], title := "Miter Limit", status := .implemented,
    note := "M and /ML set miter_limit (values under 1 are ignored, default 10); stroke.rs miter_fits measures the two segment directions in user space and cuts a miter to a bevel when 1/sin(angle/2) is over the limit (stroke.rs the_miter_limit_cuts_sharp_joins_to_bevels, executor.rs line_joins_follow_j_lj_m_and_ml); the writer emits M through canvas.rs set_miter_limit." },
  { ref := .clause [8, 4, 3, 6], title := "Line Dash Pattern", status := .implemented,
    note := "The dash array and phase are measured in user space through the inverse CTM, an empty array restores solid strokes and /D in an ExtGState is honored; the writer emits d through canvas.rs set_dash." },
  { ref := .clause [8, 4, 4], title := "Graphics State Operators", status := .implemented,
    note := "All eleven operators parse and set their state, and ri and i are accepted with no effect as the clause allows." },
  { ref := .clause [8, 4, 5], title := "Graphics State Parameter Dictionaries", status := .incomplete,
    note := "/LW /LC /LJ /ML /D /CA /ca /BM /SMask are applied from the named resource; /RI /Font /OP /op /OPM /TR /TR2 /HT /FL /SM /SA /BG /BG2 /UCR /UCR2 /TK /AIS are ignored; the writer emits /ca /CA /BM only." },
  { ref := .clause [8, 5, 2, 1], title := "General", status := .implemented,
    note := "All seven construction operators build subpaths with the current point semantics of Table 59, re starts a closed rectangle subpath, and a segment before any m starts at the origin leniently instead of erroring." },
  { ref := .clause [8, 5, 2, 2], title := "Cubic Bezier Curves", status := .implemented,
    note := "c, v and y build the four control points per Table 59 and the curve is flattened adaptively within tolerance; the writer emits c through canvas.rs curve_to." },
  { ref := .clause [8, 5, 3, 1], title := "General", status := .implemented,
    note := "Every painting operator ends the path, the closing variants close the subpath first, F is accepted as f, and n discards the path while still applying a pending clip." },
  { ref := .clause [8, 5, 3, 2], title := "Stroking", status := .implemented,
    note := "Strokes are offset quads under the full CTM with dashes, stroke patterns and the cap style applied; path.rs keeps a degenerate subpath (a closed single point or coincident points), which stroke_path paints as a filled disc under round caps and not at all under butt or square caps, while a single-point open subpath paints nothing and zero-length dashes keep their caps (stroke.rs degenerate_subpaths_paint_a_dot_only_under_round_caps, zero_length_dashes_take_the_cap_style, executor.rs tests of the same names, path.rs degenerate_subpaths_are_kept_for_the_stroker); joins follow 8.4.3.4 and 8.4.3.5." },
  { ref := .clause [8, 5, 3, 3, 1], title := "General", status := .implemented,
    note := "Open subpaths are implicitly closed before filling and coverage is anti-aliased per pixel." },
  { ref := .clause [8, 5, 3, 3, 2], title := "Nonzero Winding Number Rule", status := .implemented,
    note := "f, B and b accumulate signed winding per scanline span and paint where it is nonzero." },
  { ref := .clause [8, 5, 3, 3, 3], title := "Even-Odd Rule", status := .implemented,
    note := "f*, B* and b* count crossings and paint where the count is odd; the writer emits f* through canvas.rs fill_even_odd." },
  { ref := .clause [8, 5, 4], title := "Clipping Path Operators", status := .implemented,
    note := "W and W* mark a pending clip that intersects the current clip after the following painting operator (n included), nested clips and a clip straddling a form (cases nested_clips, clip_straddling_a_form) intersect correctly, and the writer emits W n and W* n through canvas.rs clip." },
  { ref := .clause [8, 6, 2], title := "Colour Values", status := .implemented,
    note := "Each family declares its component count and decode range, operands are clamped to the space's range, and every colour ends as RGB for compositing." },
  { ref := .clause [8, 6, 3], title := "Colour Space Families", status := .implemented,
    note := "The device, CIE-based (CalGray, CalRGB, Lab, ICCBased) and special (Indexed, Separation, DeviceN, Pattern) families all parse from name or array form, with unknown names falling back to DeviceGray." },
  { ref := .clause [8, 6, 4, 2], title := "DeviceGray Colour Space", status := .implemented,
    note := "g/G and DeviceGray image samples convert gray to equal RGB channels (case device_colorspaces)." },
  { ref := .clause [8, 6, 4, 3], title := "DeviceRGB Colour Space", status := .implemented,
    note := "rg/RG and DeviceRGB image samples pass through unchanged." },
  { ref := .clause [8, 6, 4, 4], title := "DeviceCMYK Colour Space", status := .incomplete,
    note := "k/K and CMYK images convert, but by a deliberate multiplicative formula (1-c)(1-k) rather than the clause's 1 - min(1, c + k), chosen so deep colours keep their hue." },
  { ref := .clause [8, 6, 5, 2], title := "CalGray Colour Spaces", status := .implemented,
    note := "/Gamma and /WhitePoint are read and gray decodes through XYZ to sRGB; /BlackPoint is ignored and a bare /CalGray name reads as DeviceGray." },
  { ref := .clause [8, 6, 5, 3], title := "CalRGB Colour Spaces", status := .implemented,
    note := "Per-channel /Gamma and the column-major /Matrix map to XYZ with identity defaults; /BlackPoint is ignored and a bare /CalRGB name or a dictionary without /WhitePoint falls back to DeviceRGB." },
  { ref := .clause [8, 6, 5, 4], title := "Lab Colour Spaces", status := .implemented,
    note := "/Range defaults to plus or minus 100, the default image decode is the Lab range, and the inverse transfer follows the clause's two-branch form (the source comment at math.rs cites the clause)." },
  { ref := .clause [8, 6, 5, 5], title := "ICCBased Colour Spaces", status := .implemented,
    note := "Matrix/TRC, lut8/lut16 and lutAtoB profiles transform through the PCS, sRGB-equivalent profiles take the device path, /N mismatches and unparseable profiles fall back to /N or /Alternate, and /Range and /Metadata are ignored." },
  { ref := .clause [8, 6, 5, 6], title := "Default Colour Spaces", status := .notImplemented,
    note := "No code reads /DefaultGray, /DefaultRGB or /DefaultCMYK from the /ColorSpace resource dictionary, so device colours are never remapped." },
  { ref := .clause [8, 6, 5, 7], title := "Implicit Conversion of CIE-Based Colour Spaces", status := .implemented,
    note := "Every CIE-based colour converts to the sRGB output space through XYZ with Bradford adaptation of the declared white point; the output space is fixed to sRGB." },
  { ref := .clause [8, 6, 5, 8], title := "Rendering Intents", status := .incomplete,
    note := "ri parses and is accepted, but neither it nor /RI changes anything; the ICC pipeline uses one fixed transform regardless of the requested intent." },
  { ref := .clause [8, 6, 6, 2], title := "Pattern Colour Spaces", status := .incomplete,
    note := "/Pattern and [/Pattern base] spaces select tiling and shading patterns for path fills and strokes, but text glyphs (executor.rs) and image stencils (executor.rs) painted with a pattern colour get a mid-gray stand-in and a report entry." },
  { ref := .clause [8, 6, 6, 3], title := "Indexed Colour Spaces", status := .implemented,
    note := "String and stream lookup tables over any base (Lab and nested Indexed included) resolve, out-of-range indices clamp, and the image decode default is [0 2^bpc-1] (case indexed_image_and_stencil)." },
  { ref := .clause [8, 6, 6, 4], title := "Separation Colour Spaces", status := .implemented,
    note := "The tint transform (function types 0, 2, 3, 4) runs into the alternate space with initial tint 1.0 (crates/pdfboss-render/src/color.rs parse_with and to_rgb, executor.rs initial_color). The special colorant All ignores the alternate space and the transform and puts the tint on every colorant, gray 1 - tint on the composite output (ColorSpace::SeparationAll). None never marks the page: fills, strokes and text carry a zero-alpha colour (executor.rs fill_rgba8, stroke_rgba8), a stencil mask returns before painting (blit_image), an image in the space returns from image.rs draw, and a shading from shading.rs paint and paint_background. Not caught: a Type3 glyph that sets its own colour inside a None fill, and an Indexed space over a None base; a DeviceN whose colorants are all None belongs to 8.6.6.5. Tests: executor.rs separation_none_never_marks_the_page and separation_all_paints_the_tint_on_every_colorant, color.rs separation_all_and_none_ignore_the_alternate_and_transform." },
  { ref := .clause [8, 6, 6, 5], title := "DeviceN Colour Spaces", status := .incomplete,
    note := "n-colourant tint transforms evaluate into the alternate space, but spaces with more than 8 colourants (the clause allows 32) fall back to an ink approximation and the attributes dictionary is ignored." },
  { ref := .clause [8, 6, 6, 6], title := "Multitone Examples", status := .implemented,
    note := "Informative examples of 8.6.6.5; a two-colourant DeviceN with a sampled tint transform (the duotone shape) evaluates through the general DeviceN path." },
  { ref := .clause [8, 6, 7], title := "Overprint Control", status := .notImplemented,
    note := "Nothing reads /OP, /op or /OPM; every paint composites over the backdrop in RGB with no overprint simulation." },
  { ref := .clause [8, 6, 8], title := "Colour Operators", status := .implemented,
    note := "All twelve operators set the stroking or nonstroking space and colour, black DeviceGray is the initial colour and cs/CS applies the space's initial colour; the writer emits rg/RG/g/G/k/K through canvas.rs set_fill and 219 set_stroke." },
  { ref := .clause [8, 7, 2], title := "General Properties of Patterns", status := .implemented,
    note := "The pattern matrix maps pattern space to the default space of the page or of the form whose resource it is, not to the CTM at painting time, and loaded patterns are cached per document." },
  { ref := .clause [8, 7, 3, 1], title := "General", status := .implemented,
    note := "Table 75's /BBox, /XStep, /YStep, /Resources and /Matrix are read (a zero or missing step falls back to the bbox size), /TilingType is ignored as a spacing hint, and the tile count is capped at 65536 with a report." },
  { ref := .clause [8, 7, 3, 2], title := "Coloured Tiling Patterns", status := .implemented,
    note := "/PaintType 1 cells run with their own colour operators and inherit the paint site's blend mode and soft mask." },
  { ref := .clause [8, 7, 3, 3], title := "Uncoloured Tiling Patterns", status := .implemented,
    note := "/PaintType 2 cells paint in the scn colour given in the [/Pattern base] underlying space with the cell's own colour operators locked out." },
  { ref := .clause [8, 7, 4, 1], title := "General", status := .incomplete,
    note := "/Shading and /Matrix of a Table 76 pattern dictionary are read and the fill paints through the path with /Background, but the pattern's own /ExtGState entry is not applied." },
  { ref := .clause [8, 7, 4, 2], title := "Shading Operator", status := .implemented,
    note := "sh paints the named shading over the current clip intersected with its /BBox, ignores /Background as the clause requires, and reports a singular CTM instead of painting; the writer serializes sh at content.rs." },
  { ref := .clause [8, 7, 4, 3], title := "Shading Dictionaries", status := .implemented,
    note := "/ShadingType, /ColorSpace, /Background and /BBox are honored (/Background only behind pattern fills, per Table 78); /AntiAlias is ignored as a hint." },
  { ref := .clause [8, 7, 4, 4], title := "Colour Space: Special Considerations", status := .incomplete,
    note := "A /Function turns colour data into one parametric value and mesh vertex colours decode through the shading's space, but an /Indexed space combined with /Function and a /Pattern shading space are not rejected as the clause requires." },
  { ref := .clause [8, 7, 4, 5, 2], title := "Type 1 (Function-Based) Shadings", status := .implemented,
    note := "The 2-in function evaluates per pixel over /Domain under /Matrix and points outside the domain stay unpainted." },
  { ref := .clause [8, 7, 4, 5, 3], title := "Type 2 (Axial) Shadings", status := .implemented,
    note := "/Coords, /Domain, /Extend and a single or array-valued /Function are honored." },
  { ref := .clause [8, 7, 4, 5, 4], title := "Type 3 (Radial) Shadings", status := .implemented,
    note := "The two circles, /Domain and /Extend are honored and a negative radius is rejected; the test covers concentric circles without extension." },
  { ref := .clause [8, 7, 4, 5, 5], title := "Type 4 Shadings (Free-Form Gouraud-Shaded Triangle Meshes)", status := .implemented,
    note := "Flags 0, 1 and 2 with /BitsPerCoordinate, /BitsPerComponent, /BitsPerFlag and /Decode are read from the stream and Gouraud interpolation paints each triangle." },
  { ref := .clause [8, 7, 4, 5, 6], title := "Type 5 Shadings (Lattice-Form Gouraud-Shaded Triangle Meshes)", status := .implemented,
    note := "/VerticesPerRow rows are split into triangle pairs and painted like type 4." },
  { ref := .clause [8, 7, 4, 5, 7], title := "Type 6 Shadings (Coons Patch Meshes)", status := .implemented,
    note := "The 12 control points per patch in Table 85 order, edge sharing for flags 1 to 3, and interior points derived by the Coons formula are all handled." },
  { ref := .clause [8, 7, 4, 5, 8], title := "Type 7 Shadings (Tensor-Product Patch Meshes)", status := .implemented,
    note := "The four extra interior points are read in Table 86 order and the patch is evaluated as a bicubic tensor patch." },
  { ref := .clause [8, 8, 1], title := "General", status := .implemented,
    note := "Do dispatches on /Subtype (indirect values resolved) to image or form drawing and reports a missing or untyped XObject; the writer emits Do for images and form groups (canvas.rs draw_image, 387 draw_group)." },
  { ref := .clause [8, 8, 2], title := "PostScript XObjects", status := .outOfScope,
    note := "pdfboss does not interpret PostScript, so a /PS XObject is skipped with an Unsupported report entry, which is what the clause tells a non-PostScript reader to do." },
  { ref := .clause [8, 9, 2], title := "Image Parameters", status := .implemented,
    note := "/Width, /Height, /BitsPerComponent and /ColorSpace drive decoding; bad dimensions are rejected and short sample data reports as truncated." },
  { ref := .clause [8, 9, 3], title := "Sample Representation", status := .implemented,
    note := "1, 2, 4, 8 and 16 bit samples are read big-endian with each row padded to a whole byte, 16-bit samples scaling by 65535." },
  { ref := .clause [8, 9, 4], title := "Image Coordinate System", status := .implemented,
    note := "The image fills the unit square under the CTM with row 0 at the top edge (v = 1) by inverse mapping of each device pixel." },
  { ref := .clause [8, 9, 5, 1], title := "General", status := .incomplete,
    note := "Of Table 89 the entries Width, Height, BitsPerComponent, ColorSpace, Decode, ImageMask, Mask, SMask, SMaskInData and OC are honored, while Intent, Interpolate, Alternates, Name, StructParent, ID, OPI and Metadata are ignored." },
  { ref := .clause [8, 9, 5, 2], title := "Decode Arrays", status := .implemented,
    note := "/Decode maps native samples, stencils and the Lab and Indexed defaults per Table 90 (crates/pdfboss-render/src/image.rs decode_samples, decode_stencil), maps DCTDecode samples per component through apply_decode (so a Photoshop-style CMYK JPEG with /Decode [1 0 1 0 1 0 1 0] comes out right), and is ignored for JPXDecode as 7.4.9 asks. Tests: image.rs decode_array_inverts_gray, dct_decode_array_applies_to_jpeg_samples and dct_decode_array_inverts_photoshop_cmyk." },
  { ref := .clause [8, 9, 5, 3], title := "Image Interpolation", status := .implemented,
    note := "image.rs ImageMeta reads /Interpolate (the inline /I is expanded at content.rs) and draw_rgba samples an interpolating image bilinearly (Rgba::bilinear) wherever it is drawn larger than itself, alpha included so stencil edges soften too; without the flag magnification stays nearest-neighbour and minification keeps its box average either way (image.rs interpolated_magnification_blends_between_samples, executor.rs interpolate_blends_a_magnified_image); the clause leaves the algorithm to the reader." },
  { ref := .clause [8, 9, 5, 4], title := "Alternate Images", status := .notImplemented,
    note := "No code reads /Alternates; the base image is always drawn, which the clause permits a reader to do." },
  { ref := .clause [8, 9, 6, 1], title := "General", status := .implemented,
    note := "Stencil, explicit and colour key masking are dispatched from one place, with /SMask taking precedence over /Mask when both are present." },
  { ref := .clause [8, 9, 6, 2], title := "Stencil Masking", status := .incomplete,
    note := "/ImageMask true paints the nonstroking colour where the decoded sample is 0 (with /Decode [1 0] inverting and JPX stencils repacked to 1 bit), but a pattern nonstroking colour paints a mid-gray stand-in with a report entry." },
  { ref := .clause [8, 9, 6, 3], title := "Explicit Masking", status := .implemented,
    note := "A stream-valued /Mask must be an /ImageMask stencil, its 1 samples hide the base image and a mask of different dimensions is resampled onto the base's unit square; a non-stencil /Mask stream is reported; the test comment cites §8.9.6.4, which is not the -1 number for explicit masking." },
  { ref := .clause [8, 9, 6, 4], title := "Colour Key Masking", status := .implemented,
    note := "An array /Mask of 2n integer ranges hides samples whose raw values all fall inside, on native sample data only (DCT and JPX images decline with a report, since the clause warns the result is unpredictable there)." },
  { ref := .clause [8, 9, 7], title := "Inline Images", status := .implemented,
    note := "BI/ID/EI with the Table 93 key abbreviations, the /G /RGB /CMYK /I colour space abbreviations, the Table 94 filter abbreviations and /L are honored and a named colour space resolves through the /ColorSpace resource; the writer serializes inline images with /L." },
  { ref := .clause [8, 10, 2], title := "Form Dictionaries", status := .implemented,
    note := "/Matrix, /BBox (as a clip) and /Resources (prepended to the lookup chain with page fallback; output lib.rs cites the clause) are honored to depth 16 (cases nested_forms, form_resource_shadowing), /Group /Ref /Metadata /PieceInfo /StructParent are ignored, and the writer emits form XObjects with /BBox and /Resources at pdf.rs." },
  { ref := .clause [8, 10, 3], title := "Group XObjects", status := .incomplete,
    note := "Only the /G form of a soft mask runs as an offscreen group; a form carrying a /Group entry that is drawn with Do runs inline with no group compositing, so /S /Transparency, /CS, /I and /K have no effect." },
  { ref := .clause [8, 10, 4, 1], title := "General", status := .incomplete,
    note := "/Ref is never read, so a reference XObject paints its own proxy content as an ordinary form, which the clause permits when the referenced file is not consulted." },
  { ref := .clause [8, 10, 4, 2], title := "Printing Reference XObjects", status := .outOfScope,
    note := "Printer-side substitution of the referenced page has no meaning for a rasterizer that never opens the referenced file." },
  { ref := .clause [8, 10, 4, 3], title := "Special Considerations", status := .outOfScope,
    note := "The guidance on /Page and /ID matching against the referenced file does not apply while /Ref is not consulted." },
  { ref := .clause [8, 11, 2, 1], title := "General", status := .implemented,
    note := "A group is identified by its indirect reference and is off when the default configuration says so; /Name, /Intent and /Usage are not read." },
  { ref := .clause [8, 11, 2, 2], title := "Optional Content Membership Dictionaries", status := .implemented, ref2 := some (.clause [8, 11, 2, 3]),
    note := "/OCGs (single or array, null entries ignored) under /P AnyOn, AllOn, AnyOff, AllOff and /VE And/Or/Not expressions with nesting all evaluate, /VE taking precedence; oc.rs cites the visibility expression as §8.11.2.3." },
  { ref := .clause [8, 11, 2, 3], title := "Intent", status := .notImplemented,
    note := "No code reads /Intent on groups or configurations, so /Design groups are treated like /View groups." },
  { ref := .clause [8, 11, 3, 2], title := "Optional Content in Content Streams", status := .implemented,
    note := "BDC /OC with a named /Properties resource or an inline dictionary opens a span whose painting is suppressed while graphics state, text position and clipping still take effect, spans nest and EMC balances; text extraction applies the same gating." },
  { ref := .clause [8, 11, 3, 3], title := "Optional Content in XObjects and Annotations", status := .implemented,
    note := "An /OC entry on an image or form XObject or on an annotation dictionary hides it (counted, not reported as a drop); the code cites this as §8.11.3.5, which is not the -1 number." },
  { ref := .clause [8, 11, 4, 2], title := "Optional Content Properties Dictionary", status := .implemented,
    note := "/OCGs and the default /D configuration are read from the catalog; /Configs alternates are ignored because only /D applies when a document opens." },
  { ref := .clause [8, 11, 4, 3], title := "Optional Content Configuration Dictionaries", status := .incomplete,
    note := "/BaseState, /ON and /OFF apply in specification order, while /Intent and /AS are ignored and /Name /Creator /Order /ListMode /RBGroups /Locked are viewer UI entries with no rendering effect." },
  { ref := .clause [8, 11, 4, 4], title := "Usage and Usage Application Dictionaries", status := .notImplemented,
    note := "No code reads a group's /Usage dictionary or the configuration's /AS array, so View, Print, Export and Zoom usage never changes a group's state." },
  { ref := .clause [8, 11, 4, 5], title := "Determining the State of Optional Content Groups", status := .incomplete,
    note := "The state comes from /BaseState then /ON then /OFF of the default configuration and a document without /OCProperties shows everything, but the usage application step (/AS with the View event) is skipped." }
]

end Iso32000.Catalogue
