import Iso32000.Feature

/-!
Ledger rows for ISO 32000-1 chapter 12, Interactive Features.
-/

namespace Iso32000.Catalogue

def chapter12 : List Feature := [
  { ref := .clause [12, 2], title := "Viewer Preferences", status := .notImplemented,
    note := "The /ViewerPreferences dictionary (HideToolbar, HideMenubar, FitWindow, Direction, PrintScaling, Duplex and the rest) is never read or written; the writer's Viewer struct at crates/pdfboss-write/src/pdf.rs emits the catalog's /PageLayout, /PageMode and /OpenAction, which belong to §7.7.2." },
  { ref := .clause [12, 3, 2], title := "Destinations", status := .incomplete,
    note := "Explicit /XYZ destinations are written for links, outline items and /OpenAction; crates/pdfboss-core/src/destination.rs parses explicit destination arrays (12.3.2.2) and looks named destinations up in the /Names /Dests tree and the catalog /Dests dictionary (12.3.2.3), and Document::destination follows a /Dest or /D value of either kind; no writer API accepts a destination by name, no destination is followed to a page index, and the importer does not rewrite destinations." },
  { ref := .clause [12, 3, 2, 2], title := "Explicit Destinations", status := .implemented,
    note := "crates/pdfboss-core/src/destination.rs Destination::parse reads every Table 151 form: the page as a reference (DestinationPage::Object) or, for a remote go-to action, a 0-based number (DestinationPage::Number); Fit::Xyz, FitH, FitV, FitBH and FitBV keep a null or left-out coordinate as None (the viewer's current value) and read a zoom of 0 as null, FitR needs all four numbers, an unknown fit name or a page that is neither rejects the array; destination_with resolves an indirect array and indirect numbers while leaving the page reference a reference (tests destination.rs every_table_151_form_parses, null_zero_zoom_and_missing_parameters_keep_the_current_value, remote_destinations_carry_a_page_number, malformed_destinations_are_rejected, indirect_arrays_and_numbers_resolve). The writer emits [page /XYZ null null null] only, which the table allows; the importer copies a source /GoTo /D unchanged instead of rewriting it onto the imported page, a limitation of page assembly documented in docs/src/guide/assembling.md and pinned by crates/pdfboss-write/tests/importer.rs page_import_of_a_linked_source_carries_the_linked_page_along." },
  { ref := .clause [12, 3, 2, 3], title := "Named Destinations", status := .implemented,
    note := "crates/pdfboss-core/src/destination.rs named_destination_with looks a name up in the catalog's /Names /Dests tree (PDF 1.2, string keys, through tree.rs lookup) and then in the catalog's /Dests dictionary (PDF 1.1, name keys), taking a destination array or a dictionary whose /D holds one; named_destinations_with lists both sources sorted by name with the tree winning a duplicate; destination_value_with follows a /Dest or /D value that is an array, a name, a string or a dictionary with /D. Document::named_destination, named_destinations and destination on the sync side, AsyncDocument twins on the async side (tests destination.rs named_destinations_come_from_the_name_tree_and_the_catalog_dictionary, destination_values_follow_arrays_names_strings_and_d_dictionaries; crates/pdfboss-aio/tests/parity.rs names fixture). The writer still has no API that accepts a destination by name." },
  { ref := .clause [12, 3, 3], title := "Document Outline", status := .incomplete,
    note := "The writer emits a complete outline tree (/Outlines with /First, /Last and /Count; items with /Title, /Parent, /Prev, /Next, /First, /Last, /Count and /Dest) with every item open; nothing reads or lists an existing outline, and item /A, /SE, /C and /F are never written." },
  { ref := .clause [12, 3, 4], title := "Thumbnail Images", status := .notImplemented,
    note := "Page /Thumb images are never read, rendered or written." },
  { ref := .clause [12, 3, 5], title := "Collections", status := .notImplemented,
    note := "The catalog /Collection dictionary and collection schemas are never read or written (the only Collection identifiers in the code are CJK CMap character collections)." },
  { ref := .clause [12, 4, 2], title := "Page Labels", status := .incomplete,
    note := "The writer emits the /PageLabels number tree with /S, /P and /St per range and validates the page-0 range, duplicate first pages and start_at; no reader parses /PageLabels or computes a page's label, so the CLI, TUI and Python bindings never show labels." },
  { ref := .clause [12, 4, 3], title := "Articles", status := .notImplemented,
    note := "Article threads (the catalog /Threads array, thread and bead dictionaries) are never read or written." },
  { ref := .clause [12, 4, 4], title := "Presentations", status := .notImplemented,
    note := "Page /Trans transition dictionaries (Table 162), /Dur and /PresSteps are never read or written; the writer's FullScreen page mode is a §7.7.2 catalog entry, and playing a presentation is viewer behavior." },
  { ref := .clause [12, 4, 4, 2], title := "Sub-page Navigation", status := .outOfScope,
    note := "Navigation nodes (/PresSteps) drive keyboard-stepped presentation playback, which needs a viewer; pdfboss neither reads nor writes them." },
  { ref := .clause [12, 5, 2], title := "Annotation Dictionaries", status := .incomplete,
    note := "The renderer reads /Subtype, /Rect, /F, /AP, /AS and /OC, the element listings (core, aio, TUI, Python) expose only /Subtype per annotation, and the writer emits /Type, /Subtype, /Rect, /Border and /A for links; /Contents, /P, /NM, /M, /C and /StructParent are never read or written." },
  { ref := .clause [12, 5, 3], title := "Annotation Flags", status := .incomplete,
    note := "Hidden (bit 2) and NoView (bit 6) suppress painting and /OC gating is honored; Invisible, Print, NoZoom, NoRotate, ReadOnly, Locked, ToggleNoView and LockedContents are ignored, so NoRotate annotations turn with a rotated page and the Print flag never affects output." },
  { ref := .clause [12, 5, 4], title := "Border Styles", status := .incomplete,
    note := "The writer puts /Border [0 0 0] on every link so no border shows, and no test asserts that entry; the renderer never reads /Border or /BS, so an annotation with a border style but no /AP paints nothing." },
  { ref := .clause [12, 5, 5], title := "Appearance Streams", status := .implemented,
    note := "The /AP /N normal appearance is selected (through /AS for a state dictionary, a single-state dictionary needing no /AS), its /BBox transformed by /Matrix is fitted onto the normalized /Rect per the clause's algorithm and run as a form XObject, and a declared appearance that cannot be read or placed is reported; /R and /D are pointer states a rasterizer does not show." },
  { ref := .clause [12, 5, 6], title := "Annotation Types", status := .incomplete,
    note := "Assessed as a group: the renderer is subtype-blind and paints every type through its /AP /N appearance, the only special handling being that /Popup annotations are skipped, /AS state selection serves Widget check boxes and radio buttons, and pdfboss-write emits /Link annotations; no type-specific key is read and no appearance is synthesized when /AP is missing." },
  { ref := .clause [12, 5, 6, 2], title := "Markup Annotations", status := .notImplemented,
    note := "No Table 170 entry (/T, /Popup, /CA, /RC, /CreationDate, /IRT, /Subj, /RT, /IT, /ExData) is read, and in particular the /CA constant opacity is not applied when the appearance stream is painted." },
  { ref := .clause [12, 5, 6, 3], title := "Annotation States", status := .notImplemented,
    note := "/State and /StateModel on reply annotations are never read, so review status is not exposed." },
  { ref := .clause [12, 5, 6, 4], title := "Text Annotations", status := .incomplete,
    note := "Painted only through the group /AP path (tested with /Stamp and Widget fixtures, not /Text); /Open and /Name are ignored, no icon is synthesized without /AP, and the fixed-size NoZoom/NoRotate behavior the clause expects is not applied." },
  { ref := .clause [12, 5, 6, 5], title := "Link Annotations", status := .implemented,
    note := "Link annotations with /Rect, /Border [0 0 0] and a /URI or /GoTo action are written from Rust, Python, Markdown and the TOML manifest and read back structurally, and a Link without /AP paints nothing; /Dest on the annotation itself, /H, /PA and /QuadPoints are not written or read, and text extraction does not report link targets." },
  { ref := .clause [12, 5, 6, 6], title := "Free Text Annotations", status := .incomplete,
    note := "Painted only through the group /AP path; /DA, /Q, /RC, /DS, /CL, /IT, /BE and /RD are ignored and no appearance is generated from them." },
  { ref := .clause [12, 5, 6, 7], title := "Line Annotations", status := .incomplete,
    note := "Painted only through the group /AP path; /L, /LE, /IC, /LL, /LLE, /Cap and /Measure are ignored and no line is drawn without /AP." },
  { ref := .clause [12, 5, 6, 8], title := "Square and Circle Annotations", status := .incomplete,
    note := "Painted only through the group /AP path; /IC, /BE and /RD are ignored and no shape is drawn without /AP." },
  { ref := .clause [12, 5, 6, 9], title := "Polygon and Polyline Annotations", status := .incomplete,
    note := "Painted only through the group /AP path; /Vertices, /LE, /BE, /IC, /IT and /Measure are ignored." },
  { ref := .clause [12, 5, 6, 10], title := "Text Markup Annotations", status := .incomplete,
    note := "Painted only through the group /AP path; /QuadPoints are never read, so highlights, underlines, squiggles and strike-outs without /AP paint nothing and text extraction does not report marked-up spans." },
  { ref := .clause [12, 5, 6, 11], title := "Caret Annotations", status := .incomplete,
    note := "Painted only through the group /AP path; /RD and /Sy are ignored." },
  { ref := .clause [12, 5, 6, 12], title := "/Stamp annotations", status := .implemented,
    note := "/Stamp fixtures are the group's main test subject: the /AP appearance is fitted onto /Rect, hidden and OC-gated ones stay silent, and unreadable ones are reported; the /Name icon is not synthesized when /AP is absent." },
  { ref := .clause [12, 5, 6, 13], title := "Ink Annotations", status := .incomplete,
    note := "Painted only through the group /AP path; /InkList and /BS are ignored, so an ink annotation without /AP paints nothing." },
  { ref := .clause [12, 5, 6, 14], title := "Pop-up Annotations", status := .implemented,
    note := "Pop-up annotations are skipped by subtype even when they carry an /AP, which matches a static page render where the pop-up window is viewer UI; /Open and /Parent are not read." },
  { ref := .clause [12, 5, 6, 15], title := "File Attachment Annotations", status := .incomplete,
    note := "Painted only through the group /AP path; /FS and /Name are ignored and the attached file is not extracted (the writer's Attachment type is the document-level /EmbeddedFiles name tree of §7.11.4, not an annotation)." },
  { ref := .clause [12, 5, 6, 16], title := "Sound Annotations", status := .incomplete,
    note := "Painted only through the group /AP path; /Sound and /Name are ignored and playback is viewer behavior." },
  { ref := .clause [12, 5, 6, 17], title := "Movie Annotations", status := .incomplete,
    note := "Painted only through the group /AP path; /Movie, /A and /T are ignored and playback is viewer behavior." },
  { ref := .clause [12, 5, 6, 18], title := "Screen Annotations", status := .incomplete,
    note := "Painted only through the group /AP path; /MK, /A and /AA are ignored and media playback is viewer behavior." },
  { ref := .clause [12, 5, 6, 19], title := "Widget Annotations", status := .implemented,
    note := "A widget's appearance comes from /AP /N with /AS selecting among the state dictionary's streams, and an /AS naming no state is reported as a dropped annotation; /H, /MK and /BS are not read, so no appearance is generated for a widget lacking /AP." },
  { ref := .clause [12, 5, 6, 20], title := "Printer’s Mark Annotations", status := .incomplete,
    note := "Painted through the group /AP path like any other annotation; /MN is ignored and there is no print-versus-display distinction, so marks always show." },
  { ref := .clause [12, 5, 6, 21], title := "Trap Network Annotations", status := .incomplete,
    note := "Painted through the group /AP path; /LastModified, /Version, /AnnotStates and /FontFauxing are ignored and the page /LastModified consistency rule is not checked." },
  { ref := .clause [12, 5, 6, 22], title := "Watermark Annotations", status := .incomplete,
    note := "Painted through the group /AP path with the page; the /FixedPrint dictionary (/Matrix, /H, /V) is ignored, and the overlay command in crates/pdfboss-write/src/update.rs adds page content rather than a /Watermark annotation." },
  { ref := .clause [12, 5, 6, 23], title := "Redaction Annotations", status := .incomplete,
    note := "Painted through the group /AP path; /QuadPoints, /IC, /RO, /OverlayText, /Repeat, /DA and /Q are ignored, and applying a redaction (removing the content beneath) is not offered." },
  { ref := .clause [12, 6, 2], title := "Action Dictionaries", status := .incomplete,
    note := "The writer emits /URI and /GoTo action dictionaries (/S plus the type's own entries) on link annotations and tests read them back; /Next chaining is never written or followed and no reader parses an arbitrary action dictionary." },
  { ref := .clause [12, 6, 3], title := "Trigger Events", status := .incomplete,
    note := "The catalog /OpenAction is written as an explicit destination to the open_to page and range-checked; additional-actions (/AA) dictionaries on the catalog, pages, annotations and fields are never read or written, and firing triggers is viewer behavior." },
  { ref := .clause [12, 6, 4], title := "Action Types", status := .incomplete,
    note := "Only /URI and /GoTo actions are written; the fourteen other action types are neither written nor read, and no action of any type is executed." },
  { ref := .clause [12, 6, 4, 2], title := "Go-To Actions", status := .implemented,
    note := "/GoTo actions with /S /GoTo and an explicit /D destination are written for page-target links with the target page range-checked, and the action is read back in tests; on read a /GoTo is never followed (viewer behavior) and the importer copies it unchanged." },
  { ref := .clause [12, 6, 4, 3], title := "Remote Go-To Actions", status := .notImplemented,
    note := "No /GoToR action is written or read." },
  { ref := .clause [12, 6, 4, 4], title := "Embedded Go-To Actions", status := .notImplemented,
    note := "No /GoToE action or target dictionary is written or read." },
  { ref := .clause [12, 6, 4, 5], title := "Launch Actions", status := .notImplemented,
    note := "No /Launch action is written or read; launching an application would be viewer behavior in any case." },
  { ref := .clause [12, 6, 4, 6], title := "Thread Actions", status := .outOfScope,
    note := "Thread actions step through article beads inside a viewer; pdfboss executes no actions and does not model article threads." },
  { ref := .clause [12, 6, 4, 7], title := "URI Actions", status := .implemented,
    note := "/URI actions with /S /URI and the URI as a text string are written for external links from every writer front end and read back structurally in tests; /IsMap and the catalog-level /URI base dictionary are not handled, and text extraction does not report URIs." },
  { ref := .clause [12, 6, 4, 8], title := "Sound Actions", status := .outOfScope,
    note := "Sound playback needs a viewer with audio output; pdfboss executes no actions." },
  { ref := .clause [12, 6, 4, 9], title := "Movie Actions", status := .outOfScope,
    note := "Movie playback needs a viewer with media output; pdfboss executes no actions." },
  { ref := .clause [12, 6, 4, 10], title := "Hide Actions", status := .outOfScope,
    note := "Hiding or showing annotations at run time is viewer state; the renderer honors only the static Hidden flag." },
  { ref := .clause [12, 6, 4, 11], title := "Named Actions", status := .outOfScope,
    note := "NextPage, PrevPage, FirstPage and LastPage are viewer navigation; pdfboss executes no actions." },
  { ref := .clause [12, 6, 4, 12], title := "Set-OCG-State Actions", status := .outOfScope,
    note := "Toggling optional content groups at run time is viewer state; the renderer applies only the document's default /OCProperties /D configuration." },
  { ref := .clause [12, 6, 4, 13], title := "Rendition Actions", status := .outOfScope,
    note := "Multimedia rendition playback needs a viewer; pdfboss executes no actions." },
  { ref := .clause [12, 6, 4, 14], title := "Transition Actions", status := .outOfScope,
    note := "Page transitions are presentation playback inside a viewer; pdfboss executes no actions." },
  { ref := .clause [12, 6, 4, 15], title := "Go-To-3D-View Actions", status := .outOfScope,
    note := "3D artwork views need a 3D-capable viewer; pdfboss neither renders 3D streams nor executes actions." },
  { ref := .clause [12, 6, 4, 16], title := "JavaScript Actions", status := .outOfScope,
    note := "pdfboss has no JavaScript engine and never executes document scripts." },
  { ref := .clause [12, 7, 2], title := "Interactive Form Dictionary", status := .notImplemented,
    note := "The catalog /AcroForm dictionary (/Fields, /NeedAppearances, /SigFlags, /CO, /DR, /DA, /Q, /XFA) is never read or written; widgets are painted only from their own /AP." },
  { ref := .clause [12, 7, 3], title := "Field Dictionaries", status := .notImplemented,
    note := "Field dictionaries (Table 220: /FT, /Parent, /Kids, /T, /TU, /TM, /Ff, /V, /DV, /AA) are never read or written; only a merged widget's /AP is rendered." },
  { ref := .clause [12, 7, 3, 2], title := "Field Names", status := .notImplemented,
    note := "Fully qualified field names from the /T chain are never computed." },
  { ref := .clause [12, 7, 3, 3], title := "Variable Text", status := .notImplemented,
    note := "/DA, /Q, /DS and /RV are never read and no appearance stream is generated for text-bearing fields, so /NeedAppearances documents show only pre-existing /AP streams." },
  { ref := .clause [12, 7, 3, 4], title := "Rich Text Strings", status := .notImplemented,
    note := "/RV rich text is never parsed." },
  { ref := .clause [12, 7, 4], title := "Field Types", status := .incomplete,
    note := "Only the widget-level /AS state selection that check boxes and radio buttons rely on is handled; /FT, /V, /Ff and /Opt are never read for any field type." },
  { ref := .clause [12, 7, 4, 2], title := "Button Fields", status := .incomplete,
    note := "Check box and radio button appearance states are selected through /AS; the button flags (Pushbutton, Radio, NoToggleToOff, RadiosInUnison) and /V are never read." },
  { ref := .clause [12, 7, 4, 2, 2], title := "Pushbuttons", status := .notImplemented,
    note := "A pushbutton's /MK caption and icon entries are never read; only a pre-existing /AP paints through the generic widget path." },
  { ref := .clause [12, 7, 4, 2, 3], title := "Check Boxes", status := .incomplete,
    note := "The on or off appearance is selected by /AS from the /AP /N state dictionary (tested with an /On state); the field's /V, /Opt export values and /Ff are never read, so the checked state is not exposed as data." },
  { ref := .clause [12, 7, 4, 2, 4], title := "Radio Buttons", status := .incomplete,
    note := "Each kid widget's appearance is selected by /AS like a check box; the parent field's /V, /Opt and the NoToggleToOff and RadiosInUnison flags are never read." },
  { ref := .clause [12, 7, 4, 3], title := "Text Fields", status := .notImplemented,
    note := "/V, /MaxLen and the text-field flags are never read and no appearance is generated, so a text field shows only a pre-existing /AP." },
  { ref := .clause [12, 7, 4, 4], title := "Choice Fields", status := .notImplemented,
    note := "/Opt, /TI, /I, /V and the choice-field flags are never read." },
  { ref := .clause [12, 7, 4, 5], title := "Signature Fields", status := .notImplemented,
    note := "A signature field's /V signature dictionary, /Lock and /SV are never read." },
  { ref := .clause [12, 7, 5], title := "Form Actions", status := .outOfScope,
    note := "Submit, reset and import-data actions need a viewer, a form-filling state and a network; pdfboss executes no actions." },
  { ref := .clause [12, 7, 5, 2], title := "Submit-Form Action", status := .outOfScope,
    note := "Submitting field data over HTTP is viewer behavior; pdfboss executes no actions." },
  { ref := .clause [12, 7, 5, 3], title := "Reset-Form Action", status := .outOfScope,
    note := "Resetting fields to their defaults needs a form-filling state; pdfboss executes no actions." },
  { ref := .clause [12, 7, 5, 4], title := "Import-Data Action", status := .outOfScope,
    note := "Importing FDF data into a form needs a form-filling state; pdfboss executes no actions." },
  { ref := .clause [12, 7, 6], title := "Named Pages", status := .notImplemented,
    note := "The /Names /Pages and /Names /Templates name trees are never read or written." },
  { ref := .clause [12, 7, 7], title := "Forms Data Format", status := .notImplemented,
    note := "No FDF file is parsed or written anywhere in the code." },
  { ref := .clause [12, 7, 7, 2], title := "FDF File Structure", status := .notImplemented,
    note := "The document loader recognizes only %PDF headers and never reads an FDF header, body or trailer." },
  { ref := .clause [12, 7, 7, 2, 2], title := "FDF Header", status := .notImplemented,
    note := "The %FDF header is not recognized." },
  { ref := .clause [12, 7, 7, 2, 3], title := "FDF Body", status := .notImplemented,
    note := "FDF body objects are never parsed." },
  { ref := .clause [12, 7, 7, 2, 4], title := "FDF Trailer", status := .notImplemented,
    note := "An FDF trailer (/Root only, no xref) is never parsed." },
  { ref := .clause [12, 7, 7, 3], title := "FDF Catalog", status := .notImplemented,
    note := "The FDF catalog and its /FDF dictionary are never read or written." },
  { ref := .clause [12, 7, 7, 3, 2], title := "FDF Fields", status := .notImplemented,
    note := "FDF field dictionaries are never read or written." },
  { ref := .clause [12, 7, 7, 3, 3], title := "FDF Pages", status := .notImplemented,
    note := "FDF page and template dictionaries are never read or written." },
  { ref := .clause [12, 7, 7, 3, 4], title := "FDF Annotation Dictionaries", status := .notImplemented,
    note := "FDF annotation dictionaries with /Page are never read or written." },
  { ref := .clause [12, 7, 8], title := "XFA Forms", status := .notImplemented,
    note := "The /AcroForm /XFA entry and XFA packets are never read, so an XFA document renders only its PDF page content." },
  { ref := .clause [12, 8, 1], title := "General", status := .notImplemented,
    note := "The signature dictionary (Table 252: /Filter, /SubFilter, /Contents, /ByteRange, /Reference, /M, /Name) is never read or written, and there is no signing or verification." },
  { ref := .clause [12, 8, 2], title := "Transform Methods", status := .notImplemented,
    note := "Signature reference dictionaries and their /TransformMethod are never read." },
  { ref := .clause [12, 8, 2, 2], title := "DocMDP", status := .notImplemented,
    note := "DocMDP transform parameters (/P, /V) are never read." },
  { ref := .clause [12, 8, 2, 2, 2], title := "Validating Signatures That Use the DocMDP Transform Method", status := .notImplemented,
    note := "No DocMDP validation exists, and the incremental-update writer in crates/pdfboss-write/src/update.rs appends changes without checking for a certifying signature." },
  { ref := .clause [12, 8, 2, 3], title := "UR", status := .notImplemented,
    note := "Usage-rights transform parameters are never read." },
  { ref := .clause [12, 8, 2, 4], title := "FieldMDP", status := .notImplemented,
    note := "FieldMDP transform parameters (/Action, /Fields) are never read." },
  { ref := .clause [12, 8, 3], title := "Signature Interoperability", status := .notImplemented,
    note := "No /SubFilter value is recognized and no signature bytes are decoded." },
  { ref := .clause [12, 8, 3, 2], title := "PKCS#1 Signatures", status := .notImplemented,
    note := "adbe.x509.rsa_sha1 signatures and /Cert chains are never decoded or verified." },
  { ref := .clause [12, 8, 3, 3], title := "PKCS#7 Signatures as used in ISO 32000", status := .notImplemented,
    note := "PKCS#7 signature containers are never decoded or verified." },
  { ref := .clause [12, 8, 3, 3, 2], title := "Revocation Information", status := .notImplemented,
    note := "Embedded CRL and OCSP data are never read." },
  { ref := .clause [12, 8, 4], title := "Permissions", status := .notImplemented,
    note := "The catalog /Perms dictionary (/DocMDP, /UR3) is never read; the /Perms handling in crates/pdfboss-core/src/crypt.rs is the AES-256 encryption dictionary entry of §7.6.3.3." },
  { ref := .clause [12, 8, 5], title := "Legal Content Attestations", status := .notImplemented,
    note := "The /Legal attestation dictionary is never read or written (Legal in the code is a page size)." },
  { ref := .clause [12, 9], title := "Measurement Properties", status := .notImplemented,
    note := "Viewport (/VP), /Measure and number-format dictionaries are never read or written." },
  { ref := .clause [12, 10, 1], title := "General", status := .notImplemented,
    note := "The catalog /Requirements array and requirement dictionaries (Table 266) are never read or written." },
  { ref := .clause [12, 10, 2], title := "Requirement Handlers", status := .notImplemented,
    note := "Requirement handler dictionaries (/S /JS, /S /NoOp) are never read or written." }
]

end Iso32000.Catalogue
