import Iso32000.Feature

/-!
Ledger rows for ISO 32000-1 chapter 14, Document Interchange.
-/

namespace Iso32000.Catalogue

def chapter14 : List Feature := [
  { ref := .clause [14, 2], title := "Procedure Sets", status := .notImplemented,
    note := "Nothing reads or emits /ProcSet: the reader ignores the resource (which the clause allows) and pdfboss-write never adds a /ProcSet array to the resource dictionaries it writes." },
  { ref := .clause [14, 3, 2], title := "Metadata Streams", status := .incomplete,
    note := "The writer emits an unfiltered /Type /Metadata /Subtype /XML packet on the catalog and rewrites it on update, and the reader honors EncryptMetadata false for that stream, but no reader path parses XMP (Document::metadata reads only /Info) and metadata streams on pages, XObjects or other components are neither read nor written." },
  { ref := .clause [14, 3, 3], title := "Document Information Dictionary", status := .incomplete,
    note := "Title, Author, Subject, Keywords, Creator, Producer, CreationDate and ModDate are read as decoded text strings and written back (with the XMP packet kept in step on update), but the /Trapped entry of Table 317 is neither read nor written." },
  { ref := .clause [14, 4], title := "File Identifiers", status := .implemented,
    note := "The writer emits a two-element /ID of 16-byte SHA-256-derived strings, an incremental update keeps the first half and replaces the second, the strings stay unencrypted, and the reader consumes the trailer /ID for the encryption key." },
  { ref := .clause [14, 5], title := "Page-Piece Dictionaries", status := .notImplemented,
    note := "Nothing reads or writes /PieceInfo or its /LastModified and /Private entries." },
  { ref := .clause [14, 6, 1], title := "General", status := .implemented,
    note := "MP, DP, BMC, BDC and EMC (Table 320) parse into distinct operators, and the text and render executors keep a nesting stack per content stream so EMC pops the matching open." },
  { ref := .clause [14, 6, 2], title := "Property Lists", status := .implemented,
    note := "BDC and DP operands are accepted as an inline dictionary or as a name looked up in the resource chain's /Properties subdictionary, and the named form keeps the indirect-reference identity the optional-content code keys on." },
  { ref := .clause [14, 6, 3], title := "Marked Content and Clipping", status := .incomplete,
    note := "Marked-content nesting is tracked on its own stack and EMC never touches the graphics state, so a clip set inside a sequence persists as the clause requires, but no test exercises a clipping path or q/Q pair that straddles a marked-content sequence." },
  { ref := .clause [14, 7, 2], title := "Structure Hierarchy", status := .incomplete,
    note := "The catalog's /StructTreeRoot is loaded and elements are walked through /K (single or array) and /P up to the root, but /ClassMap, /IDTree, /ParentTreeNextKey and the element entries /T, /ID, /Lang, /E and /ActualText are never read (/S and /RoleMap are, under 14.7.3, and /Alt under 14.9.3), and pdfboss-write neither emits a structure tree nor carries a base document's tree through assembly." },
  { ref := .clause [14, 7, 3], title := "Structure Types", status := .implemented,
    note := "crates/pdfboss-core/src/structure.rs reads each element's /S while placing a page's marked-content sequences (Walk::key_of) and the root's /RoleMap once per document (role_map_of, an indirect map resolved); StructureTree::mapped_type follows the map from a type name until a name it has no entry for, a chain in case a mapped name is itself mapped, a cycle leaving the name as written; StructureTree::place_with returns both names per sequence as Placement { rank, structure_type, mapped_type }, and ranks_with stays the rank-only view (tests structure.rs structure_types_are_read_and_mapped_through_the_role_map, an_element_without_a_type_places_with_none). Nothing yet classifies the mapped name as one of the standard types of 14.8.4." },
  { ref := .clause [14, 7, 4], title := "Structure Content", status := .incomplete,
    note := "Marked-content sequences are located as content items and resolved through the parent tree, but object references (OBJR) and the /Stm form of marked-content references are not handled; the depth-4 rows give the detail." },
  { ref := .clause [14, 7, 4, 2], title := "Marked-Content Sequences as Content Items", status := .incomplete,
    note := "Bare integer MCIDs (matched against the element's /Pg) and marked-content reference dictionaries with /Pg and /MCID are matched, and MCIDs are collected from BDC in page and form content, but the /Stm and /StmOwn entries of Table 324 are never consulted, so a form's sequence is told apart from the page's only by its /StructParents key." },
  { ref := .clause [14, 7, 4, 3], title := "PDF Objects as Content Items", status := .notImplemented,
    note := "Object reference dictionaries (/Type /OBJR with /Obj) are never read, so annotations and XObjects placed in the tree as whole objects are invisible to structure-order extraction." },
  { ref := .clause [14, 7, 4, 4], title := "Finding Structure Elements from Content Items", status := .incomplete,
    note := "The /ParentTree number tree (/Nums, /Kids, /Limits) is searched under the /StructParents key of the page or of a form XObject that declares its own, but the singular /StructParent key of whole-object content items is never used because OBJR items are not supported." },
  { ref := .clause [14, 7, 5], title := "Structure Attributes", status := .notImplemented,
    note := "Element /A and /C entries are never read, so no attribute object, class or revision is interpreted." },
  { ref := .clause [14, 7, 5, 2], title := "Attribute Classes", status := .notImplemented,
    note := "Neither /C on elements nor /ClassMap on the root is read." },
  { ref := .clause [14, 7, 5, 3], title := "Attribute Revision Numbers", status := .notImplemented,
    note := "Nothing reads /R on elements, attribute objects or class entries." },
  { ref := .clause [14, 7, 5, 4], title := "User Properties", status := .notImplemented,
    note := "No code recognizes /O /UserProperties attribute objects or their /P arrays." },
  { ref := .clause [14, 8, 2], title := "Tagged PDF and Page Content", status := .incomplete,
    note := "Structure-tree reading order is offered on every extraction entry point, but artifacts, annotation sequencing, reversed show strings and ActualText are not handled; the depth-4 rows give the detail." },
  { ref := .clause [14, 8, 2, 2], title := "Real Content and Artifacts", status := .implemented,
    note := "crates/pdfboss-text/src/extract.rs marks every span shown inside an /Artifact marked-content sequence: a bare BMC gives ArtifactKind::Unspecified, a BDC's property list (inline or named through /Properties) gives the /Type of Table 330 (Pagination, Layout, Page, Background) and the /Subtype (Header, Footer, Watermark), on TextSpan::artifact (Mark::artifact, marked_artifact; test lib.rs artifact_marks_reach_the_spans); the Python Span exposes artifact and artifact_subtype. crates/pdfboss-output/src/structure.rs lays pagination artifacts out apart from the real content and gives them the PageHeader or PageFooter role by their position against the page's text midline, so Markdown drops a producer-marked running head or folio on a single page while text keeps it (attach_pagination_artifacts; test lib.rs tagged_pagination_artifacts_are_page_headers_and_footers_on_one_page); the repetition heuristic still covers untagged files. /BBox and /Attached are not read, and layout, page and background artifacts are marked but not treated differently from real content." },
  { ref := .clause [14, 8, 2, 3], title := "Page Content Order", status := .incomplete,
    note := "Under ReadingOrder::StructureTree each marked-content sequence is ranked by its depth-first position in the tree and untagged content keeps its place, but annotations are never sequenced into the order and /ReversedChars is ignored." },
  { ref := .clause [14, 8, 2, 3, 2], title := "Sequencing of Annotations", status := .notImplemented,
    note := "Annotations are not part of text extraction and OBJR items are not read, so a tagged annotation never takes its place in the reading order." },
  { ref := .clause [14, 8, 2, 3, 3], title := "Reverse-Order Show Strings", status := .notImplemented,
    note := "Nothing looks for the /ReversedChars marked-content tag, so right-to-left text shown in reverse order stays reversed." },
  { ref := .clause [14, 8, 2, 4], title := "Extraction of Character Properties", status := .incomplete,
    note := "Unicode values and font style come from ToUnicode, encodings, glyph names and the FontDescriptor, but ActualText, FontFamily and FontStretch are never read; the depth-4 rows give the detail." },
  { ref := .clause [14, 8, 2, 4, 2], title := "Unicode Mapping in Tagged PDF", status := .incomplete,
    note := "Characters map through /ToUnicode first, then the /Encoding-derived table and StandardEncoding, Adobe Glyph List names, and the CIDSystemInfo ordering for CID fonts, but the /ActualText property that overrides all of these on a marked-content sequence is never read." },
  { ref := .clause [14, 8, 2, 4, 3], title := "Font Characteristics", status := .incomplete,
    note := "Weight, italic, serif and fixed-pitch come from /Flags, /FontWeight, /StemV, /ItalicAngle and the /BaseFont name, but /FontFamily and /FontStretch are never read." },
  { ref := .clause [14, 8, 2, 5], title := "Identifying Word Breaks", status := .incomplete,
    note := "Word breaks come from space glyphs and from horizontal gaps between spans, which covers the clause's positional fallback, but the tagged-PDF rules (ActualText carrying the space, breaks implied by block-level element edges) are not applied because tags are never read." },
  { ref := .clause [14, 8, 3], title := "Basic Layout Model", status := .notImplemented,
    note := "Block-level and inline-level structure elements are never identified; paragraphs, headings and tables in Markdown output come from geometry and font size, not from the tree." },
  { ref := .clause [14, 8, 4], title := "Standard Structure Types", status := .implemented,
    note := "crates/pdfboss-core/src/structure.rs StandardType names the 49 standard types with the standard's own spelling, StandardType::from_name recognizes a role-mapped name (case-sensitive, a document's own types staying None), StandardType::kind sorts each into the clause that defines it (StandardKind::Grouping, BlockLevel, InlineLevel, Illustration), and Placement::standard_type and Placement::path carry the result, with the standard-typed ancestry, for every placed marked-content sequence (tests structure.rs standard_types_are_recognized_by_name_and_grouped_by_clause, placements_carry_the_standard_typed_ancestry). What each set means for extraction is the depth-4 rows' business: the block-level set acts (14.8.4.3), the other three do not yet." },
  { ref := .clause [14, 8, 4, 2], title := "Grouping Elements", status := .notImplemented,
    note := "Document, Part, Art, Sect, Div, BlockQuote, Caption, TOC, TOCI, Index, NonStruct and Private are recognized as StandardKind::Grouping (14.8.4), but nothing acts on them: no block or section break comes from Part, Sect or Div, and NonStruct and Private content is not told apart from the rest." },
  { ref := .clause [14, 8, 4, 3], title := "Block-Level Structure Elements", status := .implemented,
    note := "Under ReadingOrder::StructureTree every span the tree reaches carries TextSpan::structure (crates/pdfboss-text/src/lib.rs Structure: the holding element's standard type and the standard-typed ancestry from Placement::path, read by crates/pdfboss-core/src/structure.rs Walk::ancestry) and crates/pdfboss-output/src/structure.rs push_tagged_blocks builds the page's blocks from it: consecutive spans of one outermost block-level element are one block, H1 to H6 a heading at that level, H a heading as deep as its Part, Art and Sect ancestors nest, L a list with an item per LI and the Lbl text as the marker (digits closed by . or ) are the number, anything else a bullet; the label stays in the item's first line and the Markdown adapter strips it by length; an item's label is its own Lbl, not a nested list's; an item without a Lbl reads its marker off its first line as an untagged page does, and a first line that is nothing but the marker stays in the layout for plain text while the Markdown adapter opens the item on the line after it), Table a table with a row per TR (THead, TBody, TFoot transparent) and a cell per TH or TD (a cell's lines joined with a space), every other block-level element a paragraph, so two P elements a line apart stay two paragraphs; spans with no block-level element go through the layout heuristics, and ruled grids are not consulted on a tagged segment (tests crates/pdfboss-output/src/lib.rs tagged_block_elements_decide_the_markdown_under_structure_tree_order, a_tagged_list_without_labels_reads_its_markers_off_the_lines, a_nested_list_keeps_its_labels_out_of_the_outer_marker, the_same_page_in_content_order_reads_by_the_layout_heuristics; crates/pdfboss-text/src/lib.rs structure_tree_order_attaches_each_span_s_standard_typed_ancestry). Not read: ColSpan, RowSpan and ListNumbering attributes (14.8.5), so every cell spans one and an unlabelled list is bulleted; a nested list's content stays inside the item holding it; a label that does not open its item's first line stays in the text as a bullet item; content order, the default, still infers headings, lists and tables from layout." },
  { ref := .clause [14, 8, 4, 4], title := "Inline-Level Structure Elements", status := .notImplemented,
    note := "Span, Quote, Note, Reference, BibEntry, Code, Link, Annot, Ruby (RB, RT, RP) and Warichu (WT, WP) are recognized as StandardKind::InlineLevel (14.8.4) but nothing acts on them: no code span, link or note comes from the tree." },
  { ref := .clause [14, 8, 4, 5], title := "Illustration Elements", status := .notImplemented,
    note := "Figure, Formula and Form are recognized as StandardKind::Illustration (14.8.4) but nothing acts on them; image extraction works from XObjects, not from the tree." },
  { ref := .clause [14, 8, 5], title := "Standard Structure Attributes", status := .notImplemented,
    note := "Attribute objects are never read, so no standard attribute owner or value is interpreted." },
  { ref := .clause [14, 8, 5, 2], title := "Standard Attribute Owners", status := .notImplemented,
    note := "The /O entry of attribute objects is never read." },
  { ref := .clause [14, 8, 5, 3], title := "Attribute Values and Inheritance", status := .notImplemented,
    note := "No attribute is read, so nothing is inherited down the tree." },
  { ref := .clause [14, 8, 5, 4], title := "Layout Attributes", status := .notImplemented,
    note := "Placement, WritingMode, BBox, spacing, color and column attributes are never read." },
  { ref := .clause [14, 8, 5, 5], title := "List Attribute", status := .notImplemented,
    note := "/ListNumbering is never read; list markers in output come from the page's text." },
  { ref := .clause [14, 8, 5, 6], title := "PrintField Attributes", status := .notImplemented,
    note := "Role, checked and Desc attributes of form-field elements are never read." },
  { ref := .clause [14, 8, 5, 7], title := "Table Attributes", status := .notImplemented,
    note := "RowSpan, ColSpan, Headers, Scope and Summary are never read; table structure in output is inferred from column gaps and rulings." },
  { ref := .clause [14, 9, 2], title := "Natural Language Specification", status := .notImplemented,
    note := "/Lang is read nowhere (catalog, structure elements or marked-content property lists), so no language is reported." },
  { ref := .clause [14, 9, 2, 2], title := "Language Identifiers", status := .notImplemented,
    note := "No language tag is parsed." },
  { ref := .clause [14, 9, 2, 3], title := "Language Specification Hierarchy", status := .notImplemented,
    note := "No /Lang lookup exists at any level." },
  { ref := .clause [14, 9, 2, 4], title := "Multi-language Text Arrays", status := .notImplemented,
    note := "Multi-language text arrays are not parsed." },
  { ref := .clause [14, 9, 3], title := "Alternate Descriptions", status := .implemented,
    note := "crates/pdfboss-text/src/extract.rs reads /Alt from a BDC's property list (inline or named through /Properties, decoded as a text string like /ActualText, Executor::marked_text_string) onto every span shown inside the sequence as TextSpan::alt, the shown text untouched, and under ReadingOrder::StructureTree a span with no description of its own takes the nearest structure element's /Alt, which crates/pdfboss-core/src/structure.rs Walk::ancestry reads on the way to the root and Placement::alt carries; the Python Span exposes alt (tests structure.rs placements_carry_the_nearest_alternate_description, crates/pdfboss-text/src/lib.rs alternate_descriptions_from_property_lists_reach_the_spans, alternate_descriptions_from_structure_elements_reach_the_spans). No output adapter renders a description yet, and a Figure that shows no text has no span to carry its /Alt." },
  { ref := .clause [14, 9, 4], title := "Replacement Text", status := .implemented,
    note := "crates/pdfboss-text/src/extract.rs reads /ActualText from a BDC's property list (inline or named through /Properties, any tag, decoded as a text string) and treats it as a character substitution for the sequence: the first string shown inside becomes one span carrying the replacement, every later string only widens that span's extent, and an empty replacement leaves the sequence without text (Mark::actual, ActualText, emit, marked_actual_text; tests lib.rs actual_text_replaces_the_shown_glyphs with the clause's Drucker example, actual_text_covers_the_whole_sequence_and_may_be_empty). /ActualText on a structure element dictionary is not read; the language escape sequences of 7.9.2.2 are not interpreted." },
  { ref := .clause [14, 9, 5], title := "Expansion of Abbreviations and Acronyms", status := .notImplemented,
    note := "/E is never read." },
  { ref := .clause [14, 10, 2], title := "Web Capture Information Dictionary", status := .outOfScope,
    note := "pdfboss reads, renders and writes PDFs and is not a web-capture tool, so /SpiderInfo is ignored." },
  { ref := .clause [14, 10, 3], title := "Content Database", status := .outOfScope,
    note := "Web capture is outside pdfboss's scope; the /IDS and /URLS name trees are ignored." },
  { ref := .clause [14, 10, 4], title := "Content Sets", status := .outOfScope,
    note := "Web capture is outside pdfboss's scope; /SPS and /SIS content sets are ignored." },
  { ref := .clause [14, 10, 5], title := "Source Information", status := .outOfScope,
    note := "Web capture is outside pdfboss's scope; source information dictionaries are ignored." },
  { ref := .clause [14, 10, 6], title := "Object Attributes Related to Web Capture", status := .outOfScope,
    note := "Web capture is outside pdfboss's scope; the /ID entry on page and XObject dictionaries is ignored (the trailer /ID is a different key and is handled under 14.4)." },
  { ref := .clause [14, 11, 2], title := "Page boxes", status := .implemented,
    note := "MediaBox, CropBox, BleedBox, TrimBox and ArtBox are read with the clause's defaults (crop falls back to media, the other three to crop), clipped to the media box and treated as non-inheritable, in the sync, async and Python APIs." },
  { ref := .clause [14, 11, 2, 2], title := "Display of page boxes", status := .incomplete,
    note := "Rendering maps the CropBox (turned by /Rotate) onto the output image as the clause's default visible area, but /BoxColorInfo is never read, no option renders the media, bleed, trim or art box instead, and no test renders a page whose CropBox is narrower than its MediaBox." },
  { ref := .clause [14, 11, 3], title := "Printer’s Marks", status := .notImplemented,
    note := "Nothing recognizes the PrinterMark annotation subtype or its /MN entry; such an annotation paints only incidentally through the generic appearance-stream path at crates/pdfboss-render/src/executor.rs, which skips only Popup, Hidden and NoView annotations." },
  { ref := .clause [14, 11, 4], title := "Separation Dictionaries", status := .notImplemented,
    note := "/SeparationInfo on page objects is never read." },
  { ref := .clause [14, 11, 5], title := "Output Intents", status := .notImplemented,
    note := "/OutputIntents on the catalog is never read, so rendering never applies an output intent's ICC profile even though pdfboss-icc could." },
  { ref := .clause [14, 11, 6], title := "Trapping Support", status := .outOfScope,
    note := "Trapping is a prepress step pdfboss does not perform; /TrapNet annotations get no special reading or painting (an appearance stream would paint like any other annotation)." },
  { ref := .clause [14, 11, 7], title := "Open Prepress Interface (OPI)", status := .outOfScope,
    note := "OPI proxy substitution is a prepress workflow pdfboss does not take part in; /OPI on image and form XObjects is ignored and the XObject itself is used." },
  { ref := .clause [14, 7, 6], title := "Example of Logical Structure", status := .outOfScope,
    note := "A worked example of a structure tree with no requirement of its own; the structure it illustrates is assessed under 14.7.2 to 14.7.5." }
]

end Iso32000.Catalogue
