import Iso32000.Feature

/-!
Ledger rows for ISO 32000-1 chapter 13, Multimedia Features.
-/

namespace Iso32000.Catalogue

def chapter13 : List Feature := [
  { ref := .clause [13, 1], title := "General", status := .outOfScope,
    note := "pdfboss parses, extracts, renders and creates PDFs and is not a viewer, so multimedia playback has no place in it." },
  { ref := .clause [13, 2], title := "Multimedia", status := .outOfScope,
    note := "No crate reads a rendition, media clip or media player dictionary; a grep for those key names finds nothing in the Rust sources." },
  { ref := .clause [13, 2, 1], title := "General", status := .outOfScope,
    note := "A Screen annotation's /AP /N appearance still paints generically through crates/pdfboss-render/src/executor.rs, but its /A rendition action and /MK are never read because playback is a viewer concern." },
  { ref := .clause [13, 2, 2], title := "Viability", status := .outOfScope,
    note := "Viability (the /MH must-honor and /BE best-effort dictionaries) only matters when choosing a player to run, which pdfboss never does." },
  { ref := .clause [13, 2, 3], title := "Renditions", status := .outOfScope,
    note := "Rendition dictionaries are never read because pdfboss does not play media." },
  { ref := .clause [13, 2, 3, 1], title := "General", status := .outOfScope,
    note := "Same as 13.2.3: no rendition dictionary is read." },
  { ref := .clause [13, 2, 3, 2], title := "Media Renditions", status := .outOfScope,
    note := "Media rendition dictionaries (/S /MR) are never read because pdfboss does not play media." },
  { ref := .clause [13, 2, 3, 3], title := "Selector Renditions", status := .outOfScope,
    note := "Selector renditions (/S /SR) are never read because pdfboss does not play media." },
  { ref := .clause [13, 2, 4], title := "Media Clip Objects", status := .outOfScope,
    note := "Media clip dictionaries are never read because pdfboss does not play media." },
  { ref := .clause [13, 2, 4, 1], title := "General", status := .outOfScope,
    note := "Same as 13.2.4: no media clip dictionary is read." },
  { ref := .clause [13, 2, 4, 2], title := "Media Clip Data", status := .outOfScope,
    note := "Media clip data (/S /MCD) and its file specification are never read; pdfboss neither extracts nor plays embedded media." },
  { ref := .clause [13, 2, 4, 3], title := "Media Clip Section", status := .outOfScope,
    note := "Media clip sections (/S /MCS) are never read because pdfboss does not play media." },
  { ref := .clause [13, 2, 5], title := "Media Play Parameters", status := .outOfScope,
    note := "Play parameters (volume, repeat, duration) only apply during playback, which pdfboss never does." },
  { ref := .clause [13, 2, 6], title := "Media Screen Parameters", status := .outOfScope,
    note := "Screen parameters (window, floating window, background) describe a viewer's playback window and are never read." },
  { ref := .clause [13, 2, 6, 1], title := "General", status := .outOfScope,
    note := "Same as 13.2.6: no screen parameter dictionary is read." },
  { ref := .clause [13, 2, 6, 2], title := "Media Offset Dictionary", status := .outOfScope,
    note := "Media offsets (time, frame, marker) are only meaningful during playback and are never read." },
  { ref := .clause [13, 2, 6, 3], title := "Timespan Dictionary", status := .outOfScope,
    note := "Timespan dictionaries are only meaningful during playback and are never read." },
  { ref := .clause [13, 2, 7], title := "Other Multimedia Objects", status := .outOfScope,
    note := "Media players, player info, software identifiers and monitor specifiers describe a viewer's environment and are never read." },
  { ref := .clause [13, 2, 7, 1], title := "General", status := .outOfScope,
    note := "Same as 13.2.7: none of these dictionaries is read." },
  { ref := .clause [13, 2, 7, 2], title := "Media Players Dictionary", status := .outOfScope,
    note := "Player selection lists (/MU, /A, /NU) are never read because pdfboss does not select or run players." },
  { ref := .clause [13, 2, 7, 3], title := "Media Player Info Dictionary", status := .outOfScope,
    note := "Player info dictionaries are never read because pdfboss does not select or run players." },
  { ref := .clause [13, 2, 7, 4], title := "Software Identifier Dictionary", status := .outOfScope,
    note := "Software identifiers are never read because pdfboss does not select or run players." },
  { ref := .clause [13, 2, 7, 4, 1], title := "General", status := .outOfScope,
    note := "Same as 13.2.7.4: no software identifier is read." },
  { ref := .clause [13, 2, 7, 4, 2], title := "Software URIs", status := .outOfScope,
    note := "Software URIs are never read because pdfboss does not select or run players." },
  { ref := .clause [13, 2, 7, 4, 3], title := "Version arrays", status := .outOfScope,
    note := "Player version arrays are never read because pdfboss does not select or run players." },
  { ref := .clause [13, 2, 7, 5], title := "Monitor Specifier", status := .outOfScope,
    note := "Monitor specifiers describe the viewer's display and are never read." },
  { ref := .clause [13, 3], title := "Sounds", status := .outOfScope,
    note := "Sound objects and a Sound annotation's /Sound stream are never read; the annotation's /AP /N appearance paints generically through crates/pdfboss-render/src/executor.rs and crates/pdfboss-core/src/elements.rs lists it by subtype like any other annotation." },
  { ref := .clause [13, 4], title := "Movies", status := .outOfScope,
    note := "Movie dictionaries and movie activation dictionaries are never read; a Movie annotation's /AP /N appearance paints generically through crates/pdfboss-render/src/executor.rs." },
  { ref := .clause [13, 5], title := "Alternate Presentations", status := .outOfScope,
    note := "The /AlternatePresentations name tree and SlideShow dictionaries are never read because pdfboss does not present documents." },
  { ref := .clause [13, 6, 1], title := "General", status := .outOfScope,
    note := "3D artwork (3D annotations, 3D streams, U3D data) is never read because pdfboss neither renders nor extracts 3D content." },
  { ref := .clause [13, 6, 3, 1], title := "General", status := .outOfScope,
    note := "3D stream dictionaries (/Type /3D) are never read; pdfboss does no 3D work." },
  { ref := .clause [13, 6, 4, 1], title := "General", status := .outOfScope,
    note := "3D view dictionaries are never read; pdfboss does no 3D work." },
  { ref := .clause [13, 6, 4, 2], title := "Projection Dictionaries", status := .outOfScope,
    note := "3D projection dictionaries are never read; pdfboss does no 3D work." },
  { ref := .clause [13, 6, 5], title := "Coordinate Systems for 3D", status := .outOfScope,
    note := "3D coordinate systems are never used; pdfboss does no 3D work." }
]

end Iso32000.Catalogue
