import Iso32000.Feature

/-!
Ledger rows for ISO 32000-1 chapters 10, Rendering, and 11, Transparency.
-/

namespace Iso32000.Catalogue

def chapter10and11 : List Feature := [
  { ref := .clause [10, 2], title := "CIE-Based Colour to Device Colour", status := .implemented,
    note := "CalRGB, CalGray, Lab and ICCBased colours convert through XYZ with Bradford adaptation into sRGB, the only output device; /BlackPoint is never read and the ri operator and /RI are parsed then discarded." },
  { ref := .clause [10, 3, 2], title := "Conversion between DeviceGray and DeviceRGB", status := .implemented,
    note := "Gray to RGB replicates the value; RGB to gray uses the clause's 0.3/0.59/0.11 weights inside blend luminosity and Rec. 601 integer weights (77/150/29 over 256) for luminosity soft masks, and no gray output device exists." },
  { ref := .clause [10, 3, 3], title := "Conversion between DeviceGray and DeviceCMYK", status := .outOfScope,
    note := "The rasterizer targets only an RGB device, so gray never converts to or from CMYK." },
  { ref := .clause [10, 3, 4], title := "Conversion from DeviceRGB to DeviceCMYK", status := .outOfScope,
    note := "There is no CMYK output device, so RGB is never converted to CMYK." },
  { ref := .clause [10, 3, 5], title := "Conversion from DeviceCMYK to DeviceRGB", status := .implemented,
    note := "Every CMYK fill, stroke and image sample converts to RGB, but on purpose with the multiplicative (1-c)(1-k) form rather than the clause's 1-min(1, c+k) so deep colours keep their hue." },
  { ref := .clause [10, 4], title := "Transfer Functions", status := .outOfScope,
    note := "ExtGState /TR and /TR2 are output-device calibration hints a screen rasterizer ignores and they are never read; the soft-mask dictionary /TR is applied and assessed under 11.6.5.2." },
  { ref := .clause [10, 5, 2], title := "Halftone Screens", status := .outOfScope,
    note := "Halftoning is a printer feature; /HT is never read and the rasterizer paints continuous-tone anti-aliased RGB." },
  { ref := .clause [10, 5, 3], title := "Spot Functions", status := .outOfScope,
    note := "No halftone screens exist, so spot functions have nothing to drive." },
  { ref := .clause [10, 5, 4], title := "Threshold Arrays", status := .outOfScope,
    note := "No halftone screens exist, so threshold arrays are never read." },
  { ref := .clause [10, 5, 5], title := "Halftone Dictionaries", status := .outOfScope,
    note := "Halftone dictionaries of every type (1, 5, 6, 10, 16) are never parsed; the code does not distinguish 10.5.5.2 to 10.5.5.6." },
  { ref := .clause [10, 6, 2], title := "Flatness Tolerance", status := .incomplete,
    note := "Curves flatten to a fixed 0.1 device-pixel error bound, which satisfies any permitted flatness, but the i operator is parsed then discarded and ExtGState /FL is never read." },
  { ref := .clause [10, 6, 3], title := "Smoothness Tolerance", status := .incomplete,
    note := "Shadings are evaluated per device pixel, so any smoothness tolerance is met, but ExtGState /SM is never read." },
  { ref := .clause [10, 6, 4], title := "Scan Conversion Rules", status := .implemented,
    note := "Anti-aliased analytic coverage (vertical subsamples, exact horizontal spans) under the nonzero and even-odd rules, clips applied as coverage masks, and open subpaths closed for filling." },
  { ref := .clause [10, 6, 5], title := "Automatic Stroke Adjustment", status := .notImplemented,
    note := "ExtGState /SA is never read; the 0.75 device-pixel minimum pen width at stroke.rs is a hairline floor, not stroke adjustment." },
  { ref := .clause [11, 2], title := "Overview of Transparency", status := .incomplete,
    note := "Constant alpha, blend modes and soft masks are painted object by object, but transparency groups (group alpha, isolated, knockout) are never composited as groups." },
  { ref := .clause [11, 3, 2], title := "Basic Notation for Compositing Computations", status := .incomplete,
    note := "Definitions only; the formula they name is assessed under 11.3.3." },
  { ref := .clause [11, 3, 3], title := "Basic Compositing Formula", status := .incomplete,
    note := "Union alpha and alpha-weighted colour follow the formula, but the blend result enters unweighted by backdrop alpha (the (1-ab)*Cs + ab*B(Cb,Cs) term is missing), so a non-Normal mode over a transparent backdrop such as an /S /Alpha mask group blends against black." },
  { ref := .clause [11, 3, 4], title := "Blending Colour Space", status := .incomplete,
    note := "Blending always happens in 8-bit device sRGB after colour conversion; a group /CS is never read, so CMYK or Lab content blends in RGB rather than its own space." },
  { ref := .clause [11, 3, 5], title := "Blend Mode", status := .implemented,
    note := "All sixteen Table 136 and 137 modes are parsed (name or array form, unknown names read as Normal) and painted on fills, strokes, glyphs, images, shadings and pattern tiles; the twelve separable formulas (32000-2 §11.3.5.2) are coded with Multiply and Screen checked against their formula, and the four non-separable modes (32000-2 §11.3.5.3) are checked against hand-computed vectors." },
  { ref := .clause [11, 3, 6], title := "Interpretation of Alpha", status := .incomplete,
    note := "One alpha per paint (coverage times constant alpha times soft mask times image sample alpha) stands in for shape and opacity, which are never carried as separate values; the difference only shows in knockout groups (11.4.6)." },
  { ref := .clause [11, 3, 7], title := "Shape and Opacity Computations", status := .incomplete,
    note := "Source shape and opacity combine as the clause asks (11.3.7.2); result shape and opacity are not tracked (11.3.7.3)." },
  { ref := .clause [11, 3, 7, 2], title := "Source Shape and Opacity", status := .implemented,
    note := "Source alpha is the product of anti-aliased object coverage, the graphics-state soft mask intersected with the clip, the constant alpha and any image sample alpha, matching fj*fm*qk with the constant shape fixed at 1." },
  { ref := .clause [11, 3, 7, 3], title := "Result Shape and Opacity", status := .incomplete,
    note := "composite_over unions alpha (as + ab*(1-as)) on the page and offscreen mask buffers, but result shape and opacity are never kept apart, so group results (11.4) cannot be formed." },
  { ref := .clause [11, 3, 8], title := "Summary of Basic Compositing Computations", status := .incomplete,
    note := "Summary only; see 11.3.3 for the missing backdrop-alpha weighting of the blend result." },
  { ref := .clause [11, 4, 2], title := "Notation for Group Compositing Computations", status := .notImplemented,
    note := "Definitions only; group compositing itself is absent (11.4.4)." },
  { ref := .clause [11, 4, 3], title := "Group Structure and Nomenclature", status := .notImplemented,
    note := "Definitions only; no group tree is built because /Group is never read (11.4.4)." },
  { ref := .clause [11, 4, 4], title := "Group Compositing Computations", status := .notImplemented,
    note := "form_frame at executor.rs reads only /Matrix, /BBox and /Resources, so a form with /Group paints straight onto the page and group alpha, blend mode and soft mask apply per object instead of to the group composite." },
  { ref := .clause [11, 4, 5], title := "Isolated Groups", status := .notImplemented,
    note := "The /Group /I flag is never read; the only render onto a fresh backdrop is the /SMask /G form (executor.rs), which belongs to 11.5." },
  { ref := .clause [11, 4, 6], title := "Knockout Groups", status := .notImplemented,
    note := "/Group /K and ExtGState /TK are never read; overlapping objects, and glyphs painted one at a time through fill_spans (executor.rs), always composite over each other." },
  { ref := .clause [11, 4, 7], title := "Page Group", status := .incomplete,
    note := "The page renders onto an opaque white pixmap, matching a page group composited against white, but the page dictionary's /Group (/CS, /I, /K) is never read." },
  { ref := .clause [11, 4, 8], title := "Summary of Group Compositing Computations", status := .notImplemented,
    note := "Summary only; see 11.4.4." },
  { ref := .clause [11, 5, 2], title := "Deriving a Soft Mask from Group Alpha", status := .implemented,
    note := "The /G form renders on a transparent offscreen page as an isolated group and its alpha channel becomes the mask." },
  { ref := .clause [11, 5, 3], title := "Deriving a Soft Mask from Group Luminosity", status := .implemented,
    note := "The group renders over an opaque black or /BC backdrop and Rec. 601 luma times alpha becomes the mask with /TR applied; /BC is read as one gray component whatever the group colour space and has no test, and luminosity is taken in device RGB rather than the group /CS." },
  { ref := .clause [11, 6, 2], title := "Specifying Source and Backdrop Colours", status := .implemented,
    note := "The source colour is the current fill or stroke colour, image sample or shading value converted to RGB, and the backdrop is the pixel already on the page or offscreen mask buffer; no group backdrop exists (11.4)." },
  { ref := .clause [11, 6, 3], title := "Specifying Blending Colour Space and Blend Mode", status := .incomplete,
    note := "/BM as a name or array is honoured, but the blending colour space is never read from a group /CS and is always device RGB." },
  { ref := .clause [11, 6, 4], title := "Specifying Shape and Opacity", status := .implemented,
    note := "Object coverage, the graphics-state soft mask and the constant alpha all feed one source alpha; see 11.6.4.2 to 11.6.4.4." },
  { ref := .clause [11, 6, 4, 2], title := "Object Shape and Opacity", status := .implemented,
    note := "Fills, strokes, glyph outlines and stencil masks contribute anti-aliased coverage as shape, and image sample alpha (/SMask, /Mask, JPX alpha) contributes opacity." },
  { ref := .clause [11, 6, 4, 3], title := "Mask Shape and Opacity", status := .implemented,
    note := "The ExtGState soft mask multiplies into the alpha of every paint (fills, strokes, glyphs, images, shadings, tiles) and follows q/Q; it is folded into one alpha rather than kept as mask opacity distinct from shape." },
  { ref := .clause [11, 6, 4, 4], title := "Constant Shape and Opacity", status := .implemented,
    note := "/ca and /CA are clamped to 0..=1 and applied to fills, glyphs, images, shadings and tiles (ca) and to strokes (CA); stroke alpha /CA has no test anywhere in the tree." },
  { ref := .clause [11, 6, 5], title := "Specifying Soft Masks", status := .incomplete,
    note := "Soft-mask dictionaries are complete (11.6.5.2); soft-mask images lack /Matte handling (11.6.5.3)." },
  { ref := .clause [11, 6, 5, 2], title := "Soft-Mask Dictionaries", status := .implemented,
    note := "/S (Alpha or Luminosity), /G rendered at the CTM in force at gs from a fresh graphics state, /BC, /TR (function, /Identity, /Default) and /SMask /None are handled with failures reported; /BC is approximated as gray and untested." },
  { ref := .clause [11, 6, 5, 3], title := "Soft-Mask Images", status := .implemented,
    note := "An image /SMask (with /Decode, any dimensions) and JPX /SMaskInData 1 and 2 give per-sample alpha; a /Matte is converted through the base image's colour space (image.rs matte_rgb) and image.rs Rgba::unmatted gives each sample its original colour back before compositing, exact for device gray and RGB and approximate through a non-linear conversion, while a mask whose dimensions differ from the base's is used as stored (image.rs matte_is_unblended_before_compositing, executor.rs matte_samples_are_unblended_before_painting)." },
  { ref := .clause [11, 6, 6], title := "Transparency Group XObjects", status := .notImplemented,
    note := "form_frame (executor.rs) never reads /Group, so /S /Transparency forms paint inline like plain forms and /CS, /I and /K have no effect; the only /S /Transparency in the tree is a test fixture at executor.rs." },
  { ref := .clause [11, 6, 7], title := "Patterns and Transparency", status := .incomplete,
    note := "Shading patterns and tiling cells take the invoking state's constant alpha, blend mode and soft mask, but a tiling cell is not composited as one transparency group, so translucent or overlapping tiles composite tile by tile." },
  { ref := .clause [11, 7, 2], title := "Colour Spaces for Transparency Groups", status := .notImplemented,
    note := "Group /CS is never read and no group colour space exists; everything blends in device RGB." },
  { ref := .clause [11, 7, 3], title := "Spot Colours and Transparency", status := .outOfScope,
    note := "Separation and DeviceN colours pass through their tint transforms into RGB before compositing, so this screen device has no spot colourants to composite separately." },
  { ref := .clause [11, 7, 4], title := "Overprinting and Transparency", status := .outOfScope,
    note := "/OP, /op and /OPM are never read; overprint simulation is a print-preview feature the screen rasterizer does not attempt, which covers 11.7.4.2 to 11.7.4.5 alike." },
  { ref := .clause [11, 7, 5], title := "Rendering Parameters and Transparency", status := .notImplemented,
    note := "Neither halftone and transfer parameters (11.7.5.2) nor rendering intents (11.7.5.3) take part in compositing." },
  { ref := .clause [11, 7, 5, 2], title := "Halftone and Transfer Function", status := .outOfScope,
    note := "No halftones or graphics-state transfer functions exist (10.4, 10.5), so there is nothing to apply after group compositing." },
  { ref := .clause [11, 7, 5, 3], title := "Rendering Intent and Colour Conversions", status := .notImplemented,
    note := "ri and /RI are parsed then discarded (executor.rs), the ICC crate uses only a profile's default transform (icc lib.rs), and all colour converts to sRGB at paint time rather than at group compositing." }
]

end Iso32000.Catalogue
