import Iso32000.Feature

/-!
Ledger rows for ISO 32000-1 chapter 7, Syntax.
-/

namespace Iso32000.Catalogue

def chapter7 : List Feature := [
  { ref := .clause [7, 2, 2], title := "Character Set", status := .implemented,
    note := "Table 1 white-space bytes, Table 2 delimiters and regular bytes classify every token; the writer escapes delimiter bytes in names (crates/pdfboss-write/src/ser.rs write_name)." },
  { ref := .clause [7, 2, 3], title := "Comments", status := .implemented,
    note := "A percent sign skips to CR or LF everywhere tokens are read; the header and startxref comments are read by their own scanners (document.rs, xref.rs)." },
  { ref := .clause [7, 3, 2], title := "Boolean Objects", status := .implemented,
    note := "The true and false keywords parse to Object::Bool; the writer serializes them (crates/pdfboss-write/src/ser.rs, test ser.rs scalars_serialize_exactly)." },
  { ref := .clause [7, 3, 3], title := "Numeric Objects", status := .implemented,
    note := "Integers read as i64 and reals as f64 with sign and leading-dot forms, malformed runs cleaned leniently; the writer emits plain decimals without exponents (crates/pdfboss-write/src/ser.rs, test ser.rs real_pins_exact_bytes)." },
  { ref := .clause [7, 3, 4], title := "String Objects", status := .implemented,
    note := "Both string forms decode to raw bytes in Object::String; the writer picks the literal or hex form from the bytes (crates/pdfboss-write/src/ser.rs write_string, tests ser.rs strings_use_literal_form_with_escapes and ser.rs strings_fall_back_to_hex_form)." },
  { ref := .clause [7, 3, 4, 2], title := "Literal Strings", status := .implemented,
    note := "Balanced parentheses, all Table 3 escapes, one to three digit octal codes, backslash line continuation and EOL normalization to LF are covered, and an unknown escape drops the backslash as the clause requires." },
  { ref := .clause [7, 3, 4, 3], title := "Hexadecimal Strings", status := .implemented,
    note := "White space inside the brackets is skipped and an odd final digit is read as the high nibble; non-hex bytes are skipped leniently (the implementation comment at lexer.rs cites the clause, the tests do not)." },
  { ref := .clause [7, 3, 5], title := "Name Objects", status := .implemented,
    note := "Number-sign escapes decode, the empty name is accepted and a bad escape is kept literally; the writer escapes bytes outside 0x21-0x7E and rejects NUL (crates/pdfboss-write/src/ser.rs and ser.rs, tests ser.rs names_escape_irregular_bytes and ser.rs names_with_nul_bytes_are_rejected)." },
  { ref := .clause [7, 3, 6], title := "Array Objects", status := .implemented,
    note := "Heterogeneous nested arrays parse with a nesting cap and an unterminated array ends leniently at end of input; the writer separates items with single spaces (crates/pdfboss-write/src/ser.rs arrays_separate_items_with_single_spaces)." },
  { ref := .clause [7, 3, 7], title := "Dictionary Objects", status := .implemented,
    note := "Name keys with any value parse, a non-name key is dropped and a value-less key maps to null; a null-valued entry is stored rather than treated as absent and a repeated key keeps the last value, while the writer sorts keys bytewise (crates/pdfboss-write/src/ser.rs dicts_sort_keys_bytewise)." },
  { ref := .clause [7, 3, 8], title := "Stream Objects", status := .incomplete,
    note := "The dictionary plus stream/endstream body, /Length, /Filter and /DecodeParms are handled, but the external-file entries (/F, /FFilter, /FDecodeParms) and /DL are never read; the writer refuses a stream nested inside another object (crates/pdfboss-write/src/error.rs, test ser.rs nested_streams_are_errors)." },
  { ref := .clause [7, 3, 8, 1], title := "General", status := .incomplete,
    note := "Of the Table 5 entries only /Length, /Filter and /DecodeParms are consumed, so stream data kept in an external file (/F with /FFilter and /FDecodeParms) is never fetched and /DL is ignored." },
  { ref := .clause [7, 3, 8, 2], title := "Stream Extent", status := .implemented,
    note := "The EOL after the stream keyword (CRLF or LF, a lone CR tolerated) is skipped, a direct or indirect /Length is verified against the following endstream, and a wrong or missing length falls back to a scan for endstream that trims one trailing EOL." },
  { ref := .clause [7, 3, 9], title := "Null Object", status := .implemented,
    note := "The null keyword parses to Object::Null and a reference to a missing object resolves to null; a null /Filter reads as no filter." },
  { ref := .clause [7, 3, 10], title := "Indirect Objects", status := .implemented,
    note := "Object headers, endobj (lenient when missing), the N G R lookahead and the rule that a reference to a missing object is null are all covered, with generation mismatches tolerated; the writer emits N G R and numbers objects densely (crates/pdfboss-write/src/ser.rs refs_serialize_as_num_gen_r)." },
  { ref := .clause [7, 4, 2], title := "ASCIIHexDecode Filter", status := .implemented,
    note := "Hex pairs with white space skipped, the > EOD marker and an odd final digit padded with zero decode, and the AHx abbreviation is accepted." },
  { ref := .clause [7, 4, 3], title := "ASCII85Decode Filter", status := .implemented,
    note := "Five-character groups, the z shorthand, the ~> EOD marker, partial final groups and interior white space decode, with a leading <~ tolerated." },
  { ref := .clause [7, 4, 4], title := "LZWDecode and FlateDecode Filters", status := .incomplete,
    note := "Both filters decode with their parameters and PNG predictors, but TIFF predictor 2 is undone for 8-bit components only (see 7.4.4.4); the writer compresses streams with Flate (crates/pdfboss-write/src/writer.rs compress_into, test writer.rs compressed_stream_round_trips)." },
  { ref := .clause [7, 4, 4, 1], title := "General", status := .implemented,
    note := "FlateDecode accepts zlib (RFC 1950) and raw deflate data, returns the decoded prefix of a truncated stream and caps output size; LZWDecode is assessed under 7.4.4.2." },
  { ref := .clause [7, 4, 4, 2], title := "Details of LZW Encoding", status := .implemented,
    note := "Codes grow from 9 to 12 bits, clear-table (256) and EOD (257) codes, the KwKwK case and both EarlyChange width schedules decode; corrupt or truncated data keeps the decoded prefix." },
  { ref := .clause [7, 4, 4, 3], title := "LZWDecode and FlateDecode Parameters", status := .implemented,
    note := "Table 8 parameters (/Predictor, /Colors, /BitsPerComponent, /Columns, /EarlyChange) are read with their defaults, /DecodeParms arrays stay aligned with the /Filter array and indirect values resolve." },
  { ref := .clause [7, 4, 4, 4], title := "LZW and Flate Predictor Functions", status := .incomplete,
    note := "PNG predictors 10 to 15 (per-row filter byte, all five filter types, sub-byte samples) and TIFF predictor 2 at 8 bits per component decode; TIFF predictor 2 with 1, 2, 4 or 16 bits per component passes the data through undecoded." },
  { ref := .clause [7, 4, 5], title := "RunLengthDecode Filter", status := .implemented,
    note := "Literal runs (0-127), repeat runs (129-255) and the 128 EOD byte decode, a missing EOD is tolerated and output size is capped." },
  { ref := .clause [7, 4, 6], title := "CCITTFaxDecode Filter", status := .implemented,
    note := "Group 4 (K<0), pure 1-D Group 3 (K=0) and mixed Group 3 (K>0) decode to packed 1-bit samples, reading /K, /Columns, /Rows, /EncodedByteAlign, /BlackIs1 and /EndOfLine with Table 11 defaults; /EndOfBlock and /DamagedRowsBeforeError are described in comments but never read, the row count being inferred from the data instead." },
  { ref := .clause [7, 4, 7], title := "JBIG2Decode Filter", status := .implemented,
    note := "The PDF embedded-stream organization with /JBIG2Globals decodes through a cleanroom codec (generic, refinement, symbol/text, pattern/halftone regions and MMR) and 1 bits are inverted to DeviceGray ink as the clause requires; the filter must be last in the chain." },
  { ref := .clause [7, 4, 8], title := "DCTDecode Filter", status := .incomplete,
    note := "The filter chain passes JPEG bytes through and the image layer decodes them with the external jpeg-decoder 0.3 crate (Gray, RGB and Adobe-inverted CMYK layouts), but the /ColorTransform decode parameter this clause defines is never read and /Decode arrays are not applied to JPEG data." },
  { ref := .clause [7, 4, 9], title := "JPXDecode Filter", status := .implemented,
    note := "A cleanroom JPEG 2000 decoder handles the codestream, the colour space comes from the codestream when the dictionary has none, /Decode is ignored except for image masks, /SMaskInData 1 and 2 (image.rs) and Indexed over JPX are honoured, and the filter must be last in the chain." },
  { ref := .clause [7, 4, 10], title := "Crypt Filter", status := .implemented,
    note := "The decryptor reads a stream's own /Crypt filter when it loads the object (crates/pdfboss-core/src/crypt.rs stream_crypt_filter): /Name Identity, or no /Name, leaves the data as stored, a name from /CF decrypts with that filter's method and the file key as is, as the clause asks, and a name matching no /CF entry leaves the data as stored; decode_stream then treats Crypt as a no-op (crates/pdfboss-core/src/filters/mod.rs). Tests: crypt.rs a_stream_crypt_filter_naming_identity_is_left_as_stored, a_stream_crypt_filter_without_a_name_means_identity and a_stream_crypt_filter_naming_a_cf_entry_uses_the_file_key_as_is; filters/mod.rs crypt_filter_leaves_data_as_stored and crypt_filter_first_in_a_chain_is_a_no_op." },
  { ref := .clause [7, 5, 2], title := "File Header", status := .implemented,
    note := "The %PDF-M.m header is searched in the first 1 KiB and defaults to 1.4 when absent, without shifting xref offsets for a header not at byte 0 (the recovery scan covers that case); the writer emits the header and a binary comment line (crates/pdfboss-write/src/writer.rs write_header, test writer.rs table_mode_minimal_document_loads)." },
  { ref := .clause [7, 5, 3], title := "File Body", status := .implemented,
    note := "Indirect objects are read at their cross-reference offsets, and when the table is unusable a whole-file scan for N G obj headers rebuilds it with the last occurrence winning." },
  { ref := .clause [7, 5, 4], title := "Cross-Reference Table", status := .implemented,
    note := "Subsection headers and n/f entries are read token-wise so 19 and 21 byte lines load as well as 20 byte ones, though the free-entry linked list is not tracked; the writer emits exact 20-byte entries (crates/pdfboss-write/src/writer.rs emit_table and writer.rs table_offset, test writer.rs table_offsets_past_ten_digits_are_rejected)." },
  { ref := .clause [7, 5, 5], title := "File Trailer", status := .implemented,
    note := "The startxref offset is found in the last 1 KiB widening to 64 KiB and the trailer's /Size, /Root, /Info, /ID and /Encrypt are consumed, with %%EOF itself not required; the writer emits the trailer, startxref and %%EOF (crates/pdfboss-write/src/writer.rs trailer_dict)." },
  { ref := .clause [7, 5, 6], title := "Incremental Updates", status := .implemented,
    note := "The newest section wins and /Prev is followed with a visited-offset loop guard; the writer appends update sections chained by /Prev (crates/pdfboss-write/src/update.rs cites the clause; tests crates/pdfboss-write/tests/update_append.rs two_appends_chain and tests/test_update.py test_update_appends_and_preserves_bytes)." },
  { ref := .clause [7, 5, 7], title := "Object Streams", status := .implemented,
    note := "The /N and /First header pairs are parsed once and members are addressed by index and never decrypted separately, while /Extends is not needed for reading and not read; the writer packs objects into streams (crates/pdfboss-write/src/writer.rs build_objstm, test writer.rs object_streams_pack_and_resolve)." },
  { ref := .clause [7, 5, 8], title := "Cross-Reference Streams", status := .implemented,
    note := "Cross-reference streams are decoded through the ordinary filter chain and their dictionary serves as the trailer; the writer emits them by default (crates/pdfboss-write/src/writer.rs emit_stream, test writer.rs stream_mode_minimal_document_loads)." },
  { ref := .clause [7, 5, 8, 2], title := "Cross-Reference Stream Dictionary", status := .implemented,
    note := "/W field widths of 0 to 8 bytes, /Size, /Index (defaulting to [0 Size]) and /Prev are read; /Type /XRef is not checked." },
  { ref := .clause [7, 5, 8, 3], title := "Cross-Reference Stream Data", status := .implemented,
    note := "Type 0, 1 and 2 entries are decoded as big-endian fields per /W, a zero-width type field defaults to type 1, unknown types read as free and truncated data ends the table leniently." },
  { ref := .clause [7, 5, 8, 4], title := "Compatibility with Applications That Do Not Support Compressed Reference Streams", status := .implemented,
    note := "A classic trailer's /XRefStm section merges ahead of its own table and before /Prev is followed (the fixture crates/pdfboss-testkit/src/lib.rs hybrid_doc documents the clause); the writer appends a classic table to a hybrid base (crates/pdfboss-write/tests/update_append.rs hybrid_base_appends_a_classic_table)." },
  { ref := .clause [7, 6, 2], title := "General Encryption Algorithm", status := .implemented,
    note := "Algorithm 1 per-object keys (with the sAlT suffix for AES-128) and the direct AES-256 file key decrypt strings and stream bodies, object-stream members are left alone and /Encrypt and /ID are never decrypted; the writer encrypts the same way with AES-256 (crates/pdfboss-write/src/writer.rs new_encrypted; tests crates/pdfboss-write/tests/encrypt.rs encrypt_dict_strings_are_never_encrypted and encrypt.rs xref_stream_is_never_encrypted)." },
  { ref := .clause [7, 6, 3], title := "Standard Security Handler", status := .incomplete,
    note := "V1/V2 RC4, V4 with the V2 or AESV2 crypt filter and V5 R5/R6 AES-256 files open under user or owner passwords, but a V4 file whose stream crypt filter is /Identity is refused (see 7.6.3.2 and 7.6.5); the writer produces AES-256 R6 files (crates/pdfboss-core/src/crypt.rs aes256_encrypt_dict)." },
  { ref := .clause [7, 6, 3, 2], title := "Standard Encryption Dictionary", status := .implemented, ref2 := some (.clause [7, 6, 4, 2]),
    note := "/Filter /Standard, /V, /R, /Length, /P, /O, /U, /OE, /UE, /Perms, /EncryptMetadata, /CF, /StmF, /StrF and /EFF are read (crates/pdfboss-core/src/crypt.rs from_standard_with_password and CryptFilters::parse; tests crypt.rs string_filter_is_chosen_independently_of_the_stream_filter and embedded_file_filter_applies_to_embedded_file_streams); /SubFilter names the formats of public-key handlers (adbe.pkcs7.*), so a reader with only the Standard handler has nothing to read there." },
  { ref := .clause [7, 6, 3, 3], title := "Encryption Key Algorithm", status := .implemented, ref2 := some (.clause [7, 6, 4, 3]),
    note := "Algorithm 2 with the 32-byte pad, the 50-round MD5 for R3 and up and the R4 EncryptMetadata-false suffix derives the RC4/AES-128 key, and Algorithms 2.A and 2.B recover the AES-256 key for R5 and R6; every RC4 fixture is /V 2 /R 3 or /V 4 /R 4, so the R2 40-bit branch (crypt.rs) has no test." },
  { ref := .clause [7, 6, 3, 4], title := "Password Algorithms", status := .implemented, ref2 := some (.clause [7, 6, 4, 3]),
    note := "The user password is verified through /U (Algorithms 4 and 5), the owner password recovers the padded user password from /O (Algorithm 7) and the R5/R6 checks use /O, /U, /OE, /UE and /Perms, while Algorithm 3 (computing /O) lives only in fixtures (crates/pdfboss-testkit/src/crypt.rs) and the R2 branch (crypt.rs) is untested; the writer computes /O, /U, /OE, /UE and /Perms for R6 (crates/pdfboss-core/src/crypt.rs, test crates/pdfboss-write/tests/encrypt.rs owner_password_also_opens)." },
  { ref := .clause [7, 6, 4], title := "Public-Key Security Handlers", status := .outOfScope,
    note := "Only /Filter /Standard is accepted (crypt.rs) and every other handler fails with Error::Encrypted, because certificate and private-key handling is deliberately left out of pdfboss." },
  { ref := .clause [7, 6, 5], title := "Crypt Filters", status := .implemented,
    note := "The /CF filters are read by name with /CFM V2, AESV2 or AESV3, /StmF, /StrF and /EFF pick among them with the standard Identity filter as the default and as a pass-through (crates/pdfboss-core/src/crypt.rs CryptFilters::parse), the crypt filter /Length sets the V4 key size (v4_key_length), /CFM None or an unknown method refuses the file as Error::Encrypted, and a stream's own /Crypt filter overrides /StmF (see 7.4.10). /AuthEvent is not consulted: the password arrives when the document opens, Table 25 says readers ignore the entry for the /StmF and /StrF filters, and the Standard handler has the one file key for /EFF too. Tests: crypt.rs identity_stream_filter_leaves_streams_as_stored, string_filter_is_chosen_independently_of_the_stream_filter, embedded_file_filter_applies_to_embedded_file_streams, crypt_filter_length_sets_the_key_size and aesv3_identity_string_filter_leaves_strings_as_stored." },
  { ref := .clause [7, 7, 2], title := "Document Catalog", status := .incomplete,
    note := "Only /Pages, /OCProperties and /StructTreeRoot are read from the catalog; /Version never overrides the header and /Names, /Dests, /PageLabels, /Outlines, /Metadata, /MarkInfo, /Lang, /AcroForm, /PageMode and /PageLayout are not consumed, while the writer emits /Pages, /Outlines, /Metadata, /Names, /PageLabels and viewer entries (crates/pdfboss-write/src/pdf.rs and pdf.rs)." },
  { ref := .clause [7, 7, 3], title := "Page Tree", status := .incomplete,
    note := "The tree walk, inheritance and page count are handled, with page-level gaps listed under 7.7.3.3; the writer builds page trees (crates/pdfboss-write/src/pdf.rs, crates/pdfboss-write/src/assemble.rs cites the clause)." },
  { ref := .clause [7, 7, 3, 2], title := "Page Tree Nodes", status := .implemented,
    note := "/Kids are walked depth-first in document order, /Count is used when plausible, /Type /Page ends descent and cycles and depth are capped; /Parent is not needed for reading." },
  { ref := .clause [7, 7, 3, 3], title := "Page Objects", status := .incomplete,
    note := "/Contents (single stream or array joined by newlines with nulls skipped), the five boxes with Table 30 defaults, /Rotate, /Resources, /Annots and /StructParents are consumed; /UserUnit and the page-level /Group transparency dictionary are never read, and the viewer entries (/Dur, /Trans, /AA, /Tabs) are ignored." },
  { ref := .clause [7, 7, 3, 4], title := "Inheritance of Page Attributes", status := .implemented,
    note := "/Resources, /MediaBox, /CropBox and /Rotate flow down the /Pages nodes with the nearest ancestor winning and the non-inheritable boxes staying on the leaf (the fixture at parity.rs cites the clause, the test does not)." },
  { ref := .clause [7, 7, 4], title := "Name Dictionary", status := .notImplemented,
    note := "No consuming code reads the catalog /Names dictionary; the writer emits /Names /EmbeddedFiles (crates/pdfboss-write/src/pdf.rs, test crates/pdfboss-write/tests/roundtrip.rs attachments_sort_by_name_and_round_trip_bytes)." },
  { ref := .clause [7, 8, 2], title := "Content Streams", status := .implemented,
    note := "Operands followed by an operator are tokenized with unknown operators skipped, inline images with their abbreviations are parsed, and a /Contents array is concatenated with a newline between parts; the writer produces content streams (crates/pdfboss-write/src/canvas.rs and crates/pdfboss-write/src/content.rs)." },
  { ref := .clause [7, 8, 3], title := "Resource Dictionaries", status := .implemented,
    note := "Category/name lookups walk the resource chain innermost first (form, then caller, then page, with a page missing /Resources inheriting from /Pages), and text extraction and rendering apply the same rule." },
  { ref := .clause [7, 9, 2], title := "String Object Types", status := .implemented,
    note := "Text strings decode from UTF-16BE, UTF-8 or PDFDocEncoding by their byte-order mark (crates/pdfboss-core/src/object.rs decode_text_string) and byte strings stay raw; the writer encodes text strings as ASCII or UTF-16BE (crates/pdfboss-write/src/pdf.rs text_string cites 7.9.2.2)." },
  { ref := .clause [7, 9, 2, 2], title := "Text String Type", status := .implemented,
    note := "UTF-16BE with a BOM and the PDF 2.0 UTF-8 BOM form decode with lone surrogates and odd trailing bytes replaced by U+FFFD, while language escape sequences inside UTF-16 text are kept unchanged; the writer writes ASCII plainly and everything else as UTF-16BE with a BOM (crates/pdfboss-write/src/pdf.rs)." },
  { ref := .clause [7, 9, 2, 3], title := "PDFDocEncoded String Type", status := .implemented,
    note := "A string without a BOM decodes through the PDFDocEncoding table (crates/pdfboss-core/src/object.rs pdf_doc_char): the accents at 0x18-0x1F, the punctuation and ligatures at 0x80-0x9E and the Euro at 0xA0 map to their characters, the undefined codes become U+FFFD, and every other code agrees with Latin-1 (tests object.rs decode_pdf_doc_encoding_accents_at_0x18, decode_pdf_doc_encoding_punctuation_at_0x80, decode_pdf_doc_encoding_undefined_codes_are_replaced)." },
  { ref := .clause [7, 9, 2, 4], title := "Byte String Type", status := .implemented,
    note := "Strings are kept as raw bytes in Object::String and exposed through as_str_bytes with no character interpretation, which is what /ID, /O and /U consumers rely on." },
  { ref := .clause [7, 9, 3], title := "Text Streams", status := .notImplemented,
    note := "No consumer reads a text stream (used by JavaScript and similar viewer features); decode_text_string is only applied to string objects." },
  { ref := .clause [7, 9, 4], title := "Dates", status := .incomplete,
    note := "The core Metadata exposes /CreationDate and /ModDate as the raw D: string without parsing; only the writer crate parses and formats the D:YYYYMMDDHHmmSSOHH'mm form (Date::parse_pdf, also used when merging an existing Info dictionary at crates/pdfboss-write/src/update.rs)." },
  { ref := .clause [7, 9, 5], title := "Rectangles", status := .implemented,
    note := "Four-number arrays with indirect elements resolved are normalized so that any two opposite corners define the rectangle." },
  { ref := .clause [7, 9, 6], title := "Name Trees", status := .notImplemented,
    note := "No name-tree walker exists on the consuming side (nothing reads /Dests, /EmbeddedFiles or any other /Names tree); the writer emits a single flat /Names leaf without /Kids or /Limits (crates/pdfboss-write/src/pdf.rs)." },
  { ref := .clause [7, 9, 7], title := "Number Trees", status := .implemented,
    note := "/Nums leaves, /Kids subtrees and /Limits are honoured under a node budget for the structure /ParentTree lookup; the writer emits a /PageLabels /Nums tree (crates/pdfboss-write/src/pdf.rs, test crates/pdfboss-write/tests/roundtrip.rs page_labels_resolve_roman_front_matter_and_offset_decimal)." },
  { ref := .clause [7, 10, 2], title := "Type 0 (Sampled) Functions", status := .implemented,
    note := "/Size, /BitsPerSample of 1 to 32, /Encode and /Decode with their defaults and multilinear interpolation between the 2^m nearest samples are covered, and /Order 3 is not honoured (the clause permits linear interpolation)." },
  { ref := .clause [7, 10, 3], title := "Type 2 (Exponential Interpolation) Functions", status := .implemented,
    note := "C0 + x^N (C1 - C0) with the C0, C1 and N defaults evaluates for shadings and tint transforms, the first input only as the clause defines." },
  { ref := .clause [7, 10, 4], title := "Type 3 (Stitching) Functions", status := .implemented,
    note := "/Functions, /Bounds (k-1 of them, checked) and /Encode with its default remap the input into the selected subfunction, with subfunctions loaded under a MAX_FUNCTIONS budget." },
  { ref := .clause [7, 10, 5], title := "Type 4 (PostScript Calculator) Functions", status := .implemented,
    note := "The full Table 42 operator set (arithmetic, relational, boolean, bitwise, stack and if/ifelse compiled to jumps) is parsed from the brace-delimited program with comments skipped, and the result feeds shadings and Separation/DeviceN tint transforms." },
  { ref := .clause [7, 10, 5, 2], title := "Errors in Type 4 Functions", status := .implemented,
    note := "Syntax errors reject the function at load time, and runtime failures (stack underflow or overflow, type mismatch, division by zero and other domain errors, runaway programs) clamp every output to the bottom of /Range rather than aborting the paint." },
  { ref := .clause [7, 11, 2], title := "File Specification Strings", status := .notImplemented,
    note := "No consumer reads /F or /UF file specification strings, and the writer stores the attachment name as both /F and /UF without any platform-dependent conversion (crates/pdfboss-write/src/pdf.rs)." },
  { ref := .clause [7, 11, 3], title := "File Specification Dictionaries", status := .notImplemented,
    note := "Nothing on the consuming side reads /Type /Filespec dictionaries; the writer emits them with /F, /UF, /Desc and /EF (crates/pdfboss-write/src/pdf.rs, test crates/pdfboss-write/tests/roundtrip.rs attachments_sort_by_name_and_round_trip_bytes)." },
  { ref := .clause [7, 11, 4], title := "Embedded File Streams", status := .notImplemented,
    note := "Embedded files are never extracted or listed on the consuming side; the writer emits /Type /EmbeddedFile streams with /Subtype and /Params /Size and /ModDate but no related-files array (crates/pdfboss-write/src/pdf.rs embedded_files_dict, whose doc at pdf.rs cites the clause; tests crates/pdfboss-write/tests/roundtrip.rs attachment_params_size_and_conditional_moddate and tests/test_write.py test_multiple_attachments_and_page_labels_compose)." },
  { ref := .clause [7, 11, 5], title := "URL Specifications", status := .notImplemented,
    note := "/FS /URL file specifications are neither read nor written (crates/pdfboss-write/src/pdf.rs writes a /URI action, which belongs to chapter 12, not a file specification)." },
  { ref := .clause [7, 11, 6], title := "Collection Items", status := .notImplemented,
    note := "No /CI collection item dictionaries are read or written." },
  { ref := .clause [7, 11, 7], title := "Maintenance of File Specifications", status := .outOfScope,
    note := "This clause describes how applications that move or rename files keep specifications valid, a file-management duty pdfboss has no role in." },
  { ref := .clause [7, 12, 2], title := "Developer Extensions Dictionary", status := .notImplemented,
    note := "The catalog /Extensions dictionary is never read or written." },
  { ref := .clause [7, 12, 3], title := "BaseVersion", status := .notImplemented,
    note := "No /BaseVersion handling exists; only the header version is reported (document.rs)." },
  { ref := .clause [7, 12, 4], title := "ExtensionLevel", status := .notImplemented,
    note := "No /ExtensionLevel handling exists." }
]

end Iso32000.Catalogue
