import Iso32000.Feature

/-!
Ledger rows for ISO 32000-1 chapter 9, Text.
-/

namespace Iso32000.Catalogue

def chapter9 : List Feature := [
  { ref := .clause [9, 2, 2], title := "Basics of Showing Text", status := .implemented,
    note := "BT, Tf, Td, Tj and ET are parsed, executed for extraction and painted by the renderer; the writer emits the same five-operator sequence from Canvas::text (crates/pdfboss-write/src/canvas.rs)." },
  { ref := .clause [9, 2, 3], title := "Achieving Special Graphical Effects", status := .implemented,
    note := "The renderer paints every Tr mode of Table 106 for outline fonts: fills in the fill colour, strokes in the stroke colour through stroke_path with the graphics state's line parameters, and the clipping modes intersect the clip with the glyph outlines at ET so later content shows through the text (executor.rs clip_render_modes_intersect_the_clip_when_the_text_object_ends); SkippedKind::TextClip is no longer produced." },
  { ref := .clause [9, 2, 4], title := "Glyph Positioning and Metrics", status := .implemented,
    note := "Widths are read in 1/1000 text-space units (Type3 through /FontMatrix), the horizontal displacement w0 advances the text matrix and vertical fonts use w1 with the position vector; the writer's Standard14::text_width sums AFM widths the same way (crates/pdfboss-write/src/font.rs)." },
  { ref := .clause [9, 3, 1], title := "General", status := .implemented,
    note := "The Table 104 text state parameters live in the graphics state on both the extraction and the render side, so q/Q restore them and BT/ET leave them alone; Tf takes the font resource name and size." },
  { ref := .clause [9, 3, 2], title := "Character Spacing", status := .implemented,
    note := "Tc is added to every glyph displacement, scaled by Th horizontally and unscaled in vertical writing; only the render tests measure the Tc advance, extraction has no dedicated one." },
  { ref := .clause [9, 3, 3], title := "Word Spacing", status := .implemented,
    note := "Tw applies to the single-byte code 32 only, including composite fonts whose CMap has a one-byte codespace covering it; the writer's justified paragraphs set Tw per line and reset it (crates/pdfboss-write/src/element.rs)." },
  { ref := .clause [9, 3, 4], title := "Horizontal Scaling", status := .implemented,
    note := "Tz/100 scales horizontal advances, TJ offsets and the glyph rendering matrix and is not applied to vertical displacements; only the extraction side has an advance test." },
  { ref := .clause [9, 3, 5], title := "Leading", status := .implemented,
    note := "TL sets the leading, TD sets it to -ty, and T*, ' and \" move the line matrix down by it." },
  { ref := .clause [9, 3, 6], title := "Text Rendering Mode", status := .implemented,
    note := "executor.rs show_text and paint_glyph follow Table 106: modes 0, 2, 4, 6 fill, modes 1, 2, 5, 6 stroke each glyph after its fill in the stroke colour with the user-space line width, caps, joins and dash, modes 4 to 7 accumulate the outlines from BT (or from the Tr inside the text object) and ET intersects the clip with their nonzero union, no outlines meaning no clip, and Q restores it; mode 3 paints nothing; a Type3 font is affected by mode 3 only, so its glyphs paint in every other mode and never clip (executor.rs stroke_render_modes_paint_the_outline_in_the_stroke_colour, clip_render_modes_intersect_the_clip_when_the_text_object_ends, type3_text_ignores_every_mode_but_invisible, text_render_mode_is_restored_by_q); extraction marks modes 3 and 7 invisible." },
  { ref := .clause [9, 3, 7], title := "Text Rise", status := .implemented,
    note := "Ts shifts the glyph origin in unscaled text space and is recorded on each TextSpan; the renderer applies it in the text rendering matrix without a dedicated test." },
  { ref := .clause [9, 3, 8], title := "Text Knockout", status := .notImplemented,
    note := "The ExtGState /TK flag is never read; glyphs are composited one at a time as they paint, which matches only the TK false behavior." },
  { ref := .clause [9, 4, 1], title := "General", status := .implemented,
    note := "BT resets Tm and Tlm to identity and ET ends the object while the text state parameters survive across text objects; nested BT is not diagnosed." },
  { ref := .clause [9, 4, 2], title := "Text-Positioning Operators", status := .implemented,
    note := "Td, TD, Tm and T* update Tlm and Tm per Table 108 in both consumers; the writer positions text with Td (crates/pdfboss-write/src/canvas.rs)." },
  { ref := .clause [9, 4, 3], title := "Text-Showing Operators", status := .implemented,
    note := "Tj, TJ (number offsets as -n/1000 times Tfs and Th, or ty in vertical mode), ' and \" are all executed; TJ offsets and the two quote operators have parser tests only, no extraction or render test; the writer emits Tj." },
  { ref := .clause [9, 4, 4], title := "Text Space Details", status := .implemented,
    note := "The rendering matrix [Tfs*Th 0 0 Tfs 0 Ts] x Tm x CTM and the tx/ty displacement formulas are applied per glyph, with the vertical position vector v shifting the glyph origin." },
  { ref := .clause [9, 5], title := "Introduction to Font Data Structures", status := .implemented,
    note := "Font dictionaries dispatch on /Subtype to the Type0, Type1/MMType1, TrueType and Type3 loaders on both consuming sides; the writer emits /Type /Font dictionaries for the standard 14 (crates/pdfboss-write/src/font.rs)." },
  { ref := .clause [9, 6, 2], title := "Type 1 Fonts", status := .incomplete,
    note := "Parent row: see 9.6.2.1 (implemented), 9.6.2.2 (incomplete) and 9.6.2.3 (incomplete)." },
  { ref := .clause [9, 6, 2, 1], title := "General", status := .implemented,
    note := "Table 111 entries BaseFont, FirstChar, Widths, FontDescriptor, Encoding and ToUnicode are read (LastChar is implied by the Widths length); the writer emits Type, Subtype, BaseFont and Encoding for the standard 14 (crates/pdfboss-write/src/font.rs)." },
  { ref := .clause [9, 6, 2, 2], title := "Standard Type 1 Fonts (Standard 14 Fonts)", status := .incomplete,
    note := "The twelve text faces (plus Arial, TimesNewRoman and CourierNew aliases) get AFM widths without /Widths and Croscore substitute faces at GlyphPainting::Full (bundled only with the substitute-fonts feature, on by default in the CLI), and the writer emits them WinAnsi-encoded; Symbol and ZapfDingbats have no metrics, no built-in encoding table and no substitute, so they stay unpainted and the writer rejects every character for them (crates/pdfboss-write/src/font.rs symbol_faces_reject_every_char_for_now)." },
  { ref := .clause [9, 6, 2, 3], title := "Multiple Master Fonts", status := .incomplete,
    note := "/MMType1 is dispatched like /Type1 by the renderer and falls into the simple-font loader in extraction, but no test names an /MMType1 font." },
  { ref := .clause [9, 6, 3], title := "TrueType Fonts", status := .implemented,
    note := "Simple /TrueType fonts with a FontFile2 program are parsed (head, maxp, loca, glyf, cmap, hmtx, post) and painted at every tier with /Widths taking precedence over hmtx; extraction reads the cmap platform ids to decide the WinAnsi gap fill." },
  { ref := .clause [9, 6, 4], title := "Font Subsets", status := .implemented,
    note := "The six-uppercase-plus tag is stripped before standard-14 metric lookup, substitution and picture-font detection while extracted spans keep /BaseFont as written; the writer embeds no programs, so it never subsets." },
  { ref := .clause [9, 6, 5], title := "Type 3 Fonts", status := .implemented,
    note := "FontMatrix, CharProcs, Encoding, Widths and the font's own Resources are read, CharProcs run as nested frames, d1 glyphs ignore their own color operators and the advance comes from /Widths through FontMatrix; FontBBox is not used, and several comments cite \"9.6.5.2\", a subclause number the 32000-1 outline does not have." },
  { ref := .clause [9, 6, 6], title := "Character Encoding", status := .incomplete,
    note := "Parent row: see 9.6.6.1 (incomplete), 9.6.6.2 (incomplete), 9.6.6.3 (implemented) and 9.6.6.4 (incomplete)." },
  { ref := .clause [9, 6, 6, 1], title := "General", status := .incomplete,
    note := "Named encodings and encoding dictionaries with /BaseEncoding and /Differences are applied for WinAnsiEncoding, MacRomanEncoding and StandardEncoding; MacExpertEncoding is not implemented and silently falls back to StandardEncoding." },
  { ref := .clause [9, 6, 6, 2], title := "Encodings for Type 1 Fonts", status := .incomplete,
    note := "An embedded program's built-in /Encoding (dup/put entries or the StandardEncoding token) is the base when the PDF names none, /Differences apply over it, a named encoding outranks it, and a nonsymbolic or standard-14 font without /Encoding defaults to StandardEncoding; the built-in encodings of the non-embedded Symbol and ZapfDingbats faces are not available." },
  { ref := .clause [9, 6, 6, 3], title := "Encodings for Type 3 Fonts", status := .implemented,
    note := "The /Encoding dictionary's /Differences names select CharProcs (StandardEncoding names fill unmapped codes as a leniency); extraction decodes Type3 codes through the same simple-font encoding path." },
  { ref := .clause [9, 6, 6, 4], title := "Encodings for TrueType Fonts", status := .incomplete,
    note := "Differences names resolve through post then the glyph list into the cmap, base-encoding characters go through the (3,1) subtable, and the raw code and 0xF000+code fall back through the symbol (3,0) table; one subtable is chosen by preference instead of trying each, the (1,0) path looks up the raw code without the standard-name-to-Mac-Roman step, and in a program with no cmap every code without a post-resolvable Differences name stays at gid 0." },
  { ref := .clause [9, 7, 2], title := "CID-Keyed Fonts Overview", status := .implemented,
    note := "The code to CID (CMap) to glyph (CIDToGIDMap or CFF charset) pipeline is in place for CIDFontType0 and CIDFontType2 descendants." },
  { ref := .clause [9, 7, 3], title := "CIDSystemInfo Dictionaries", status := .incomplete,
    note := "Only /Ordering is read, to pick the Japan1, GB1, CNS1, Korea1 or KR CID-to-Unicode table; /Registry and /Supplement are ignored and the CMap-versus-CIDFont collection compatibility rule is not checked." },
  { ref := .clause [9, 7, 4], title := "CIDFonts", status := .implemented,
    note := "Parent row: see 9.7.4.1, 9.7.4.2 and 9.7.4.3, all implemented (crates/pdfboss-render/src/glyph.rs load_type0 and load_cff_cid; tests there cover each child)." },
  { ref := .clause [9, 7, 4, 1], title := "General", status := .implemented,
    note := "Table 117 entries Subtype, CIDSystemInfo, FontDescriptor, DW, W, DW2, W2 and CIDToGIDMap are read from the first descendant; BaseFont is used only as style evidence." },
  { ref := .clause [9, 7, 4, 2], title := "Glyph Selection in CIDFonts", status := .implemented,
    note := "CIDFontType2 honours /CIDToGIDMap as /Identity or a stream (crates/pdfboss-render/src/glyph.rs). CIDFontType0 maps CIDs through the CFF charset when the Top DICT carries CIDFont operators and uses the CID directly as the glyph index when it does not (glyph.rs load_cff_cid over cff.rs cid_to_gid, None for the second case). A FontFile3 of /Subtype /OpenType is read from the container's CFF table (cff.rs parse, cff_table). Tests: glyph.rs cff_cid_font_paints_at_all_embedded_not_embedded_truetype_only, cff_cid_font_over_a_non_cid_program_uses_cids_as_gids, cff_cid_font_in_an_opentype_wrapper_paints; cff.rs an_opentype_wrapped_cff_parses_from_its_cff_table." },
  { ref := .clause [9, 7, 4, 3], title := "Glyph Metrics in CIDFonts", status := .implemented,
    note := "Both forms of /W and /W2 are parsed, /DW defaults to 1000, /DW2 to [880 -1000] and the default position vector is (w0/2, vy); ranges are capped at 65536 entries as a hostile-input guard." },
  { ref := .clause [9, 7, 5], title := "CMaps", status := .implemented,
    note := "Parent row: see 9.7.5.1 to 9.7.5.4, all implemented." },
  { ref := .clause [9, 7, 5, 1], title := "General", status := .implemented,
    note := "CMaps split one to four byte codes by codespace range, map them to CIDs and carry the writing mode; the CID value domain is kept apart from the ToUnicode parser." },
  { ref := .clause [9, 7, 5, 2], title := "Predefined CMaps", status := .implemented,
    note := "All Table 118 names (20 Japan1, 14 GB1, 14 CNS1, 11 Korea1, Identity-H/V) plus UniAKR-UTF16-H load from packed Adobe data behind the predefined-cmaps feature, which is off in pdfboss-core by default but on in the CLI defaults and in pdfboss-py; without it every name but Identity falls back to the Identity assumption." },
  { ref := .clause [9, 7, 5, 3], title := "Embedded CMap Files", status := .implemented,
    note := "A CMap stream as /Encoding is parsed with its /WMode and /UseCMap chain (names or streams, depth bounded at 4) and the in-content usecmap operator; the stream dictionary's CMapName and CIDSystemInfo are not read." },
  { ref := .clause [9, 7, 5, 4], title := "CMap Example and Operator Summary", status := .implemented,
    note := "begincodespacerange, begincidchar, begincidrange, beginnotdefchar, beginnotdefrange and usecmap are executed and the remaining Table 119 operators (begincmap, endcmap, CMapName, def) are skipped as inert; the bf* operators belong to ToUnicode (9.10.3)." },
  { ref := .clause [9, 7, 6], title := "Type 0 Font Dictionaries", status := .incomplete,
    note := "Parent row: see 9.7.6.1 (implemented), 9.7.6.2 (implemented) and 9.7.6.3 (incomplete)." },
  { ref := .clause [9, 7, 6, 1], title := "General", status := .implemented,
    note := "Table 121 entries Subtype, Encoding, DescendantFonts (first element) and ToUnicode are read; BaseFont feeds style detection only." },
  { ref := .clause [9, 7, 6, 2], title := "CMap Mapping", status := .implemented,
    note := "Codes are matched byte-wise against the codespace ranges (shortest match wins) and looked up by (length, value), so equal values of different lengths stay distinct; with no codespaces at all two-byte codes are assumed." },
  { ref := .clause [9, 7, 6, 3], title := "Handling Undefined Characters", status := .incomplete,
    note := "Notdef ranges are consulted after every real mapping, an invalid code consumes the shortest codespace whose first byte fits and maps to CID 0, and CID 0 still advances by /W or /DW; the renderer never draws the notdef glyph (gid 0 is skipped and reported as NoGlyph) and with no partial match one byte is consumed instead of the shortest codespace length." },
  { ref := .clause [9, 8, 1], title := "General", status := .implemented,
    note := "Table 122 entries FontName, Flags, ItalicAngle, Ascent, Descent, CapHeight, StemV, FontWeight, MissingWidth and the three FontFile keys are consumed for metrics, style and substitution; FontBBox, XHeight, StemH, Leading, AvgWidth, MaxWidth and CharSet are not read." },
  { ref := .clause [9, 8, 2], title := "Font Descriptor Flags", status := .implemented,
    note := "FixedPitch, Serif, Nonsymbolic, Italic and ForceBold (Table 123 bits 1, 2, 6, 7 and 19) drive span style, substitute face choice and the StandardEncoding default; Symbolic, Script, AllCap and SmallCap are not consulted." },
  { ref := .clause [9, 8, 3], title := "Font Descriptors for CIDFonts", status := .notImplemented,
    note := "Parent row: see 9.8.3.1 (incomplete), 9.8.3.2 (notImplemented) and 9.8.3.3 (notImplemented)." },
  { ref := .clause [9, 8, 3, 1], title := "General", status := .incomplete,
    note := "The descendant's descriptor is read through the same Table 122 path as simple fonts (Flags, metrics, FontFile2 and FontFile3), but none of the Table 124 CIDFont-only entries (Style, Lang, FD, CIDSet) is consulted." },
  { ref := .clause [9, 8, 3, 2], title := "Style", status := .notImplemented,
    note := "The /Style dictionary and its /Panose string are never read." },
  { ref := .clause [9, 8, 3, 3], title := "FD", status := .notImplemented,
    note := "The /FD dictionary of per-class descriptors is never read; only the top-level descriptor metrics apply." },
  { ref := .clause [9, 9], title := "Embedded Font Programs", status := .incomplete,
    note := "FontFile (Type 1 as PFA or PFB, eexec decrypted), FontFile2 (TrueType) and FontFile3 as bare CFF (Type1C and CIDFontType0C) are parsed and painted; the FontFile3 /Subtype is never read, OpenType-wrapped programs (OTTO) are rejected by both parsers, Length1, Length2 and Length3 are not used, and the writer embeds no font programs." },
  { ref := .clause [9, 10, 2], title := "Mapping Character Codes to Unicode Values", status := .incomplete,
    note := "ToUnicode is consulted first, simple fonts then map through the encoding's glyph names (Adobe Glyph List, uniXXXX and uXXXX[XX] forms, underscore ligatures, period variants) and composite fonts through the collection's Uni*-UTF16-H inverse keyed by /Ordering; /ActualText marked content is never used and gXX or cidXX style glyph names are not resolved." },
  { ref := .clause [9, 10, 3], title := "ToUnicode CMaps", status := .implemented,
    note := "begincodespacerange, beginbfchar and both beginbfrange forms are parsed with UTF-16BE destinations (multi-character and surrogate pairs) for simple and Type0 fonts alike; a lone U+FFFD destination is treated as no mapping and usecmap inside a ToUnicode CMap is not followed." }
]

end Iso32000.Catalogue
